// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module AsyncQueueSource_2(
  input         clock,
                reset,
  output        io_enq_ready,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  input         io_enq_valid,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  input  [3:0]  io_enq_bits_id,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  input  [31:0] io_enq_bits_addr,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  input  [7:0]  io_enq_bits_len,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  input  [2:0]  io_enq_bits_size,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  input  [1:0]  io_enq_bits_burst,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  input         io_enq_bits_lock,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  input  [3:0]  io_enq_bits_cache,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  input  [2:0]  io_enq_bits_prot,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  input  [3:0]  io_enq_bits_qos,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [3:0]  io_async_mem_0_id,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [31:0] io_async_mem_0_addr,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [7:0]  io_async_mem_0_len,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [2:0]  io_async_mem_0_size,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [1:0]  io_async_mem_0_burst,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output        io_async_mem_0_lock,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [3:0]  io_async_mem_0_cache,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [2:0]  io_async_mem_0_prot,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [3:0]  io_async_mem_0_qos,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
                io_async_mem_1_id,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [31:0] io_async_mem_1_addr,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [7:0]  io_async_mem_1_len,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [2:0]  io_async_mem_1_size,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [1:0]  io_async_mem_1_burst,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output        io_async_mem_1_lock,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [3:0]  io_async_mem_1_cache,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [2:0]  io_async_mem_1_prot,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [3:0]  io_async_mem_1_qos,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
                io_async_mem_2_id,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [31:0] io_async_mem_2_addr,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [7:0]  io_async_mem_2_len,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [2:0]  io_async_mem_2_size,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [1:0]  io_async_mem_2_burst,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output        io_async_mem_2_lock,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [3:0]  io_async_mem_2_cache,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [2:0]  io_async_mem_2_prot,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [3:0]  io_async_mem_2_qos,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
                io_async_mem_3_id,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [31:0] io_async_mem_3_addr,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [7:0]  io_async_mem_3_len,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [2:0]  io_async_mem_3_size,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [1:0]  io_async_mem_3_burst,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output        io_async_mem_3_lock,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [3:0]  io_async_mem_3_cache,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [2:0]  io_async_mem_3_prot,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [3:0]  io_async_mem_3_qos,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
                io_async_mem_4_id,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [31:0] io_async_mem_4_addr,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [7:0]  io_async_mem_4_len,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [2:0]  io_async_mem_4_size,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [1:0]  io_async_mem_4_burst,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output        io_async_mem_4_lock,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [3:0]  io_async_mem_4_cache,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [2:0]  io_async_mem_4_prot,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [3:0]  io_async_mem_4_qos,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
                io_async_mem_5_id,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [31:0] io_async_mem_5_addr,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [7:0]  io_async_mem_5_len,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [2:0]  io_async_mem_5_size,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [1:0]  io_async_mem_5_burst,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output        io_async_mem_5_lock,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [3:0]  io_async_mem_5_cache,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [2:0]  io_async_mem_5_prot,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [3:0]  io_async_mem_5_qos,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
                io_async_mem_6_id,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [31:0] io_async_mem_6_addr,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [7:0]  io_async_mem_6_len,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [2:0]  io_async_mem_6_size,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [1:0]  io_async_mem_6_burst,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output        io_async_mem_6_lock,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [3:0]  io_async_mem_6_cache,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [2:0]  io_async_mem_6_prot,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [3:0]  io_async_mem_6_qos,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
                io_async_mem_7_id,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [31:0] io_async_mem_7_addr,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [7:0]  io_async_mem_7_len,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [2:0]  io_async_mem_7_size,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [1:0]  io_async_mem_7_burst,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output        io_async_mem_7_lock,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [3:0]  io_async_mem_7_cache,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [2:0]  io_async_mem_7_prot,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [3:0]  io_async_mem_7_qos,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  input  [3:0]  io_async_ridx,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output [3:0]  io_async_widx,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  input         io_async_safe_ridx_valid,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  output        io_async_safe_widx_valid,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
                io_async_safe_source_reset_n,	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
  input         io_async_safe_sink_reset_n	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:71:14]
);

  wire        _io_enq_ready_output;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:89:29]
  wire        _sink_valid_io_out;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:104:30]
  wire        _sink_extend_io_out;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:103:30]
  wire        _source_valid_0_io_out;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:100:32]
  wire [3:0]  _ridx_ridx_gray_io_q;	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
  reg  [3:0]  mem_0_id;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [31:0] mem_0_addr;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [7:0]  mem_0_len;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [2:0]  mem_0_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [1:0]  mem_0_burst;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg         mem_0_lock;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [3:0]  mem_0_cache;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [2:0]  mem_0_prot;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [3:0]  mem_0_qos;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [3:0]  mem_1_id;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [31:0] mem_1_addr;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [7:0]  mem_1_len;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [2:0]  mem_1_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [1:0]  mem_1_burst;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg         mem_1_lock;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [3:0]  mem_1_cache;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [2:0]  mem_1_prot;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [3:0]  mem_1_qos;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [3:0]  mem_2_id;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [31:0] mem_2_addr;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [7:0]  mem_2_len;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [2:0]  mem_2_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [1:0]  mem_2_burst;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg         mem_2_lock;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [3:0]  mem_2_cache;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [2:0]  mem_2_prot;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [3:0]  mem_2_qos;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [3:0]  mem_3_id;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [31:0] mem_3_addr;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [7:0]  mem_3_len;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [2:0]  mem_3_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [1:0]  mem_3_burst;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg         mem_3_lock;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [3:0]  mem_3_cache;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [2:0]  mem_3_prot;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [3:0]  mem_3_qos;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [3:0]  mem_4_id;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [31:0] mem_4_addr;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [7:0]  mem_4_len;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [2:0]  mem_4_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [1:0]  mem_4_burst;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg         mem_4_lock;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [3:0]  mem_4_cache;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [2:0]  mem_4_prot;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [3:0]  mem_4_qos;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [3:0]  mem_5_id;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [31:0] mem_5_addr;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [7:0]  mem_5_len;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [2:0]  mem_5_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [1:0]  mem_5_burst;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg         mem_5_lock;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [3:0]  mem_5_cache;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [2:0]  mem_5_prot;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [3:0]  mem_5_qos;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [3:0]  mem_6_id;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [31:0] mem_6_addr;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [7:0]  mem_6_len;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [2:0]  mem_6_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [1:0]  mem_6_burst;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg         mem_6_lock;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [3:0]  mem_6_cache;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [2:0]  mem_6_prot;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [3:0]  mem_6_qos;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [3:0]  mem_7_id;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [31:0] mem_7_addr;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [7:0]  mem_7_len;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [2:0]  mem_7_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [1:0]  mem_7_burst;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg         mem_7_lock;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [3:0]  mem_7_cache;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [2:0]  mem_7_prot;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  reg  [3:0]  mem_7_qos;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  wire        _widx_T_1 = _io_enq_ready_output & io_enq_valid;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:89:29, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  reg  [3:0]  widx_widx_bin;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:52:25]
  reg         ready_reg;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:88:56]
  assign _io_enq_ready_output = ready_reg & _sink_valid_io_out;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:88:56, :89:29, :104:30]
  reg  [3:0]  widx_gray;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:91:55]
  wire [2:0]  index = widx_gray[2:0] ^ {widx_gray[3], 2'h0};	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:85:{52,64,80,93}, :91:55]
  always @(posedge clock) begin
    if (_widx_T_1 & index == 3'h0) begin	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:52:25, :80:16, :85:64, :86:{22,35}, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      mem_0_id <= io_enq_bits_id;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_0_addr <= io_enq_bits_addr;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_0_len <= io_enq_bits_len;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_0_size <= io_enq_bits_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_0_burst <= io_enq_bits_burst;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_0_lock <= io_enq_bits_lock;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_0_cache <= io_enq_bits_cache;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_0_prot <= io_enq_bits_prot;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_0_qos <= io_enq_bits_qos;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
    end
    if (_widx_T_1 & index == 3'h1) begin	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16, :85:64, :86:{22,35}, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      mem_1_id <= io_enq_bits_id;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_1_addr <= io_enq_bits_addr;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_1_len <= io_enq_bits_len;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_1_size <= io_enq_bits_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_1_burst <= io_enq_bits_burst;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_1_lock <= io_enq_bits_lock;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_1_cache <= io_enq_bits_cache;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_1_prot <= io_enq_bits_prot;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_1_qos <= io_enq_bits_qos;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
    end
    if (_widx_T_1 & index == 3'h2) begin	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16, :85:64, :86:{22,35}, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      mem_2_id <= io_enq_bits_id;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_2_addr <= io_enq_bits_addr;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_2_len <= io_enq_bits_len;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_2_size <= io_enq_bits_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_2_burst <= io_enq_bits_burst;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_2_lock <= io_enq_bits_lock;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_2_cache <= io_enq_bits_cache;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_2_prot <= io_enq_bits_prot;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_2_qos <= io_enq_bits_qos;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
    end
    if (_widx_T_1 & index == 3'h3) begin	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16, :85:64, :86:{22,35}, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      mem_3_id <= io_enq_bits_id;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_3_addr <= io_enq_bits_addr;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_3_len <= io_enq_bits_len;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_3_size <= io_enq_bits_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_3_burst <= io_enq_bits_burst;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_3_lock <= io_enq_bits_lock;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_3_cache <= io_enq_bits_cache;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_3_prot <= io_enq_bits_prot;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_3_qos <= io_enq_bits_qos;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
    end
    if (_widx_T_1 & index == 3'h4) begin	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16, :85:64, :86:{22,35}, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      mem_4_id <= io_enq_bits_id;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_4_addr <= io_enq_bits_addr;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_4_len <= io_enq_bits_len;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_4_size <= io_enq_bits_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_4_burst <= io_enq_bits_burst;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_4_lock <= io_enq_bits_lock;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_4_cache <= io_enq_bits_cache;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_4_prot <= io_enq_bits_prot;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_4_qos <= io_enq_bits_qos;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
    end
    if (_widx_T_1 & index == 3'h5) begin	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16, :85:64, :86:{22,35}, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      mem_5_id <= io_enq_bits_id;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_5_addr <= io_enq_bits_addr;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_5_len <= io_enq_bits_len;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_5_size <= io_enq_bits_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_5_burst <= io_enq_bits_burst;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_5_lock <= io_enq_bits_lock;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_5_cache <= io_enq_bits_cache;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_5_prot <= io_enq_bits_prot;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_5_qos <= io_enq_bits_qos;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
    end
    if (_widx_T_1 & index == 3'h6) begin	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16, :85:64, :86:{22,35}, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      mem_6_id <= io_enq_bits_id;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_6_addr <= io_enq_bits_addr;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_6_len <= io_enq_bits_len;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_6_size <= io_enq_bits_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_6_burst <= io_enq_bits_burst;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_6_lock <= io_enq_bits_lock;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_6_cache <= io_enq_bits_cache;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_6_prot <= io_enq_bits_prot;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_6_qos <= io_enq_bits_qos;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
    end
    if (_widx_T_1 & (&index)) begin	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16, :85:64, :86:{22,35}, src/main/scala/chisel3/util/Decoupled.scala:52:35]
      mem_7_id <= io_enq_bits_id;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_7_addr <= io_enq_bits_addr;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_7_len <= io_enq_bits_len;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_7_size <= io_enq_bits_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_7_burst <= io_enq_bits_burst;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_7_lock <= io_enq_bits_lock;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_7_cache <= io_enq_bits_cache;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_7_prot <= io_enq_bits_prot;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
      mem_7_qos <= io_enq_bits_qos;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
    end
  end // always @(posedge)
  wire [3:0]  _widx_incremented_T = widx_widx_bin + {3'h0, _widx_T_1};	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:52:25, :53:43, src/main/scala/chisel3/util/Decoupled.scala:52:35]
  wire [3:0]  widx_incremented = _sink_valid_io_out ? _widx_incremented_T : 4'h0;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:53:{23,43}, :104:30]
  wire [3:0]  widx = {widx_incremented[3], widx_incremented[2:0] ^ widx_incremented[3:1]};	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:53:23, :54:{17,32}]
  always @(posedge clock or posedge reset) begin
    if (reset) begin
      widx_widx_bin <= 4'h0;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:52:25]
      ready_reg <= 1'h0;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16, :88:56]
      widx_gray <= 4'h0;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:91:55]
    end
    else begin
      if (_sink_valid_io_out)	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:104:30]
        widx_widx_bin <= _widx_incremented_T;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:52:25, :53:43]
      else	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:104:30]
        widx_widx_bin <= 4'h0;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:52:25]
      ready_reg <= _sink_valid_io_out & widx != (_ridx_ridx_gray_io_q ^ 4'hC);	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:54:17, :83:{26,34,44}, :88:56, :104:30, generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
      widx_gray <= widx;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:54:17, :91:55]
    end
  end // always @(posedge, posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:15];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [4:0] i = 5'h0; i < 5'h10; i += 5'h1) begin
          _RANDOM[i[3:0]] = `RANDOM;
        end
        mem_0_id = _RANDOM[4'h0][3:0];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_0_addr = {_RANDOM[4'h0][31:4], _RANDOM[4'h1][3:0]};	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_0_len = _RANDOM[4'h1][11:4];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_0_size = _RANDOM[4'h1][14:12];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_0_burst = _RANDOM[4'h1][16:15];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_0_lock = _RANDOM[4'h1][17];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_0_cache = _RANDOM[4'h1][21:18];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_0_prot = _RANDOM[4'h1][24:22];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_0_qos = _RANDOM[4'h1][28:25];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_1_id = {_RANDOM[4'h1][31:29], _RANDOM[4'h2][0]};	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_1_addr = {_RANDOM[4'h2][31:1], _RANDOM[4'h3][0]};	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_1_len = _RANDOM[4'h3][8:1];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_1_size = _RANDOM[4'h3][11:9];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_1_burst = _RANDOM[4'h3][13:12];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_1_lock = _RANDOM[4'h3][14];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_1_cache = _RANDOM[4'h3][18:15];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_1_prot = _RANDOM[4'h3][21:19];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_1_qos = _RANDOM[4'h3][25:22];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_2_id = _RANDOM[4'h3][29:26];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_2_addr = {_RANDOM[4'h3][31:30], _RANDOM[4'h4][29:0]};	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_2_len = {_RANDOM[4'h4][31:30], _RANDOM[4'h5][5:0]};	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_2_size = _RANDOM[4'h5][8:6];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_2_burst = _RANDOM[4'h5][10:9];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_2_lock = _RANDOM[4'h5][11];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_2_cache = _RANDOM[4'h5][15:12];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_2_prot = _RANDOM[4'h5][18:16];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_2_qos = _RANDOM[4'h5][22:19];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_3_id = _RANDOM[4'h5][26:23];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_3_addr = {_RANDOM[4'h5][31:27], _RANDOM[4'h6][26:0]};	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_3_len = {_RANDOM[4'h6][31:27], _RANDOM[4'h7][2:0]};	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_3_size = _RANDOM[4'h7][5:3];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_3_burst = _RANDOM[4'h7][7:6];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_3_lock = _RANDOM[4'h7][8];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_3_cache = _RANDOM[4'h7][12:9];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_3_prot = _RANDOM[4'h7][15:13];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_3_qos = _RANDOM[4'h7][19:16];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_4_id = _RANDOM[4'h7][23:20];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_4_addr = {_RANDOM[4'h7][31:24], _RANDOM[4'h8][23:0]};	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_4_len = _RANDOM[4'h8][31:24];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_4_size = _RANDOM[4'h9][2:0];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_4_burst = _RANDOM[4'h9][4:3];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_4_lock = _RANDOM[4'h9][5];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_4_cache = _RANDOM[4'h9][9:6];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_4_prot = _RANDOM[4'h9][12:10];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_4_qos = _RANDOM[4'h9][16:13];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_5_id = _RANDOM[4'h9][20:17];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_5_addr = {_RANDOM[4'h9][31:21], _RANDOM[4'hA][20:0]};	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_5_len = _RANDOM[4'hA][28:21];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_5_size = _RANDOM[4'hA][31:29];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_5_burst = _RANDOM[4'hB][1:0];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_5_lock = _RANDOM[4'hB][2];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_5_cache = _RANDOM[4'hB][6:3];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_5_prot = _RANDOM[4'hB][9:7];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_5_qos = _RANDOM[4'hB][13:10];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_6_id = _RANDOM[4'hB][17:14];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_6_addr = {_RANDOM[4'hB][31:18], _RANDOM[4'hC][17:0]};	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_6_len = _RANDOM[4'hC][25:18];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_6_size = _RANDOM[4'hC][28:26];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_6_burst = _RANDOM[4'hC][30:29];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_6_lock = _RANDOM[4'hC][31];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_6_cache = _RANDOM[4'hD][3:0];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_6_prot = _RANDOM[4'hD][6:4];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_6_qos = _RANDOM[4'hD][10:7];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_7_id = _RANDOM[4'hD][14:11];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_7_addr = {_RANDOM[4'hD][31:15], _RANDOM[4'hE][14:0]};	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_7_len = _RANDOM[4'hE][22:15];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_7_size = _RANDOM[4'hE][25:23];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_7_burst = _RANDOM[4'hE][27:26];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_7_lock = _RANDOM[4'hE][28];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_7_cache = {_RANDOM[4'hE][31:29], _RANDOM[4'hF][0]};	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_7_prot = _RANDOM[4'hF][3:1];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        mem_7_qos = _RANDOM[4'hF][7:4];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
        widx_widx_bin = _RANDOM[4'hF][11:8];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:52:25, :80:16]
        ready_reg = _RANDOM[4'hF][12];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16, :88:56]
        widx_gray = _RANDOM[4'hF][16:13];	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16, :91:55]
      `endif // RANDOMIZE_REG_INIT
      if (reset) begin
        widx_widx_bin = 4'h0;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:52:25]
        ready_reg = 1'h0;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16, :88:56]
        widx_gray = 4'h0;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:91:55]
      end
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  AsyncResetSynchronizerShiftReg_w4_d3_i0 ridx_ridx_gray (	// @[generators/rocket-chip/src/main/scala/util/ShiftReg.scala:45:23]
    .clock (clock),
    .reset (reset),
    .io_d  (io_async_ridx),
    .io_q  (_ridx_ridx_gray_io_q)
  );
  AsyncValidSync source_valid_0 (	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:100:32]
    .io_in  (1'h1),	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:79:28]
    .io_out (_source_valid_0_io_out),
    .clock  (clock),
    .reset  (reset | ~io_async_safe_sink_reset_n)	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:105:{43,46}]
  );
  AsyncValidSync source_valid_1 (	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:101:32]
    .io_in  (_source_valid_0_io_out),	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:100:32]
    .io_out (io_async_safe_widx_valid),
    .clock  (clock),
    .reset  (reset | ~io_async_safe_sink_reset_n)	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:105:46, :106:43]
  );
  AsyncValidSync sink_extend (	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:103:30]
    .io_in  (io_async_safe_ridx_valid),
    .io_out (_sink_extend_io_out),
    .clock  (clock),
    .reset  (reset | ~io_async_safe_sink_reset_n)	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:105:46, :107:43]
  );
  AsyncValidSync sink_valid (	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:104:30]
    .io_in  (_sink_extend_io_out),	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:103:30]
    .io_out (_sink_valid_io_out),
    .clock  (clock),
    .reset  (reset)
  );
  assign io_enq_ready = _io_enq_ready_output;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:89:29]
  assign io_async_mem_0_id = mem_0_id;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_0_addr = mem_0_addr;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_0_len = mem_0_len;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_0_size = mem_0_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_0_burst = mem_0_burst;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_0_lock = mem_0_lock;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_0_cache = mem_0_cache;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_0_prot = mem_0_prot;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_0_qos = mem_0_qos;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_1_id = mem_1_id;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_1_addr = mem_1_addr;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_1_len = mem_1_len;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_1_size = mem_1_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_1_burst = mem_1_burst;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_1_lock = mem_1_lock;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_1_cache = mem_1_cache;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_1_prot = mem_1_prot;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_1_qos = mem_1_qos;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_2_id = mem_2_id;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_2_addr = mem_2_addr;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_2_len = mem_2_len;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_2_size = mem_2_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_2_burst = mem_2_burst;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_2_lock = mem_2_lock;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_2_cache = mem_2_cache;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_2_prot = mem_2_prot;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_2_qos = mem_2_qos;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_3_id = mem_3_id;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_3_addr = mem_3_addr;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_3_len = mem_3_len;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_3_size = mem_3_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_3_burst = mem_3_burst;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_3_lock = mem_3_lock;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_3_cache = mem_3_cache;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_3_prot = mem_3_prot;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_3_qos = mem_3_qos;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_4_id = mem_4_id;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_4_addr = mem_4_addr;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_4_len = mem_4_len;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_4_size = mem_4_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_4_burst = mem_4_burst;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_4_lock = mem_4_lock;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_4_cache = mem_4_cache;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_4_prot = mem_4_prot;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_4_qos = mem_4_qos;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_5_id = mem_5_id;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_5_addr = mem_5_addr;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_5_len = mem_5_len;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_5_size = mem_5_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_5_burst = mem_5_burst;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_5_lock = mem_5_lock;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_5_cache = mem_5_cache;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_5_prot = mem_5_prot;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_5_qos = mem_5_qos;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_6_id = mem_6_id;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_6_addr = mem_6_addr;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_6_len = mem_6_len;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_6_size = mem_6_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_6_burst = mem_6_burst;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_6_lock = mem_6_lock;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_6_cache = mem_6_cache;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_6_prot = mem_6_prot;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_6_qos = mem_6_qos;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_7_id = mem_7_id;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_7_addr = mem_7_addr;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_7_len = mem_7_len;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_7_size = mem_7_size;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_7_burst = mem_7_burst;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_7_lock = mem_7_lock;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_7_cache = mem_7_cache;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_7_prot = mem_7_prot;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_mem_7_qos = mem_7_qos;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:80:16]
  assign io_async_widx = widx_gray;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:91:55]
  assign io_async_safe_source_reset_n = ~reset;	// @[generators/rocket-chip/src/main/scala/util/AsyncQueue.scala:121:27]
endmodule

