// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module FrontBus(
  input         auto_subsystem_fbus_clock_groups_in_member_subsystem_fbus_0_clock,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_subsystem_fbus_clock_groups_in_member_subsystem_fbus_0_reset,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_serial_tl_clock_in_clock,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_tlserial_manager_crossing_in_a_ready,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_tlserial_manager_crossing_in_a_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_tlserial_manager_crossing_in_a_bits_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_tlserial_manager_crossing_in_a_bits_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_tlserial_manager_crossing_in_a_bits_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_tlserial_manager_crossing_in_a_bits_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [30:0] auto_tlserial_manager_crossing_in_a_bits_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [7:0]  auto_tlserial_manager_crossing_in_a_bits_mask,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [63:0] auto_tlserial_manager_crossing_in_a_bits_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_tlserial_manager_crossing_in_a_bits_corrupt,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_tlserial_manager_crossing_in_d_ready,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_tlserial_manager_crossing_in_d_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]  auto_tlserial_manager_crossing_in_d_bits_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [1:0]  auto_tlserial_manager_crossing_in_d_bits_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]  auto_tlserial_manager_crossing_in_d_bits_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]  auto_tlserial_manager_crossing_in_d_bits_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_tlserial_manager_crossing_in_d_bits_sink,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_tlserial_manager_crossing_in_d_bits_denied,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [63:0] auto_tlserial_manager_crossing_in_d_bits_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_tlserial_manager_crossing_in_d_bits_corrupt,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_bus_xing_out_a_ready,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_bus_xing_out_a_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [2:0]  auto_bus_xing_out_a_bits_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_bus_xing_out_a_bits_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_bus_xing_out_a_bits_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [4:0]  auto_bus_xing_out_a_bits_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [31:0] auto_bus_xing_out_a_bits_address,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [7:0]  auto_bus_xing_out_a_bits_mask,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [63:0] auto_bus_xing_out_a_bits_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_bus_xing_out_a_bits_corrupt,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_bus_xing_out_d_ready,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_bus_xing_out_d_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_bus_xing_out_d_bits_opcode,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [1:0]  auto_bus_xing_out_d_bits_param,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_bus_xing_out_d_bits_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [4:0]  auto_bus_xing_out_d_bits_source,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [1:0]  auto_bus_xing_out_d_bits_sink,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_bus_xing_out_d_bits_denied,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [63:0] auto_bus_xing_out_d_bits_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_bus_xing_out_d_bits_corrupt,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        uart_tsi_io_uart_txd,	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:42:27]
  input         uart_tsi_io_uart_rxd,	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:42:27]
  output        uart_tsi_io_dropped,	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:42:27]
  output [3:0]  uart_tsi_io_tsi2tl_state,	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:42:27]
  output        serial_tl_clock,	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:116:24]
                serial_tl_bits_in_ready,	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:116:24]
  input         serial_tl_bits_in_valid,	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:116:24]
  input  [3:0]  serial_tl_bits_in_bits,	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:116:24]
  input         serial_tl_bits_out_ready,	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:116:24]
  output        serial_tl_bits_out_valid,	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:116:24]
  output [3:0]  serial_tl_bits_out_bits	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:116:24]
);

  wire        _in_async_io_enq_ready;	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:133:28]
  wire        _in_async_io_deq_valid;	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:133:28]
  wire [3:0]  _in_async_io_deq_bits;	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:133:28]
  wire        _out_async_io_enq_ready;	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:126:29]
  wire        _outer_reset_catcher_io_sync_reset;	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
  wire        _width_adapter_io_narrow_in_ready;	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:39:33]
  wire        _width_adapter_io_narrow_out_valid;	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:39:33]
  wire [7:0]  _width_adapter_io_narrow_out_bits;	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:39:33]
  wire        _width_adapter_io_wide_in_ready;	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:39:33]
  wire        _width_adapter_io_wide_out_valid;	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:39:33]
  wire [31:0] _width_adapter_io_wide_out_bits;	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:39:33]
  wire        _uart_to_serial_io_serial_in_ready;	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:38:34]
  wire        _uart_to_serial_io_serial_out_valid;	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:38:34]
  wire [7:0]  _uart_to_serial_io_serial_out_bits;	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:38:34]
  wire        _coupler_from_port_named_serial_tl_ctrl_auto_buffer_in_a_ready;	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
  wire        _coupler_from_port_named_serial_tl_ctrl_auto_buffer_in_d_valid;	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
  wire [2:0]  _coupler_from_port_named_serial_tl_ctrl_auto_buffer_in_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
  wire [1:0]  _coupler_from_port_named_serial_tl_ctrl_auto_buffer_in_d_bits_param;	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
  wire [2:0]  _coupler_from_port_named_serial_tl_ctrl_auto_buffer_in_d_bits_size;	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
  wire [3:0]  _coupler_from_port_named_serial_tl_ctrl_auto_buffer_in_d_bits_source;	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
  wire [1:0]  _coupler_from_port_named_serial_tl_ctrl_auto_buffer_in_d_bits_sink;	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
  wire        _coupler_from_port_named_serial_tl_ctrl_auto_buffer_in_d_bits_denied;	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
  wire [63:0] _coupler_from_port_named_serial_tl_ctrl_auto_buffer_in_d_bits_data;	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
  wire        _coupler_from_port_named_serial_tl_ctrl_auto_buffer_in_d_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
  wire        _coupler_from_port_named_serial_tl_ctrl_auto_tl_out_a_valid;	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
  wire [2:0]  _coupler_from_port_named_serial_tl_ctrl_auto_tl_out_a_bits_opcode;	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
  wire [2:0]  _coupler_from_port_named_serial_tl_ctrl_auto_tl_out_a_bits_param;	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
  wire [2:0]  _coupler_from_port_named_serial_tl_ctrl_auto_tl_out_a_bits_size;	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
  wire [3:0]  _coupler_from_port_named_serial_tl_ctrl_auto_tl_out_a_bits_source;	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
  wire [31:0] _coupler_from_port_named_serial_tl_ctrl_auto_tl_out_a_bits_address;	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
  wire [7:0]  _coupler_from_port_named_serial_tl_ctrl_auto_tl_out_a_bits_mask;	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
  wire [63:0] _coupler_from_port_named_serial_tl_ctrl_auto_tl_out_a_bits_data;	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
  wire        _coupler_from_port_named_serial_tl_ctrl_auto_tl_out_a_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
  wire        _coupler_from_port_named_serial_tl_ctrl_auto_tl_out_d_ready;	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
  wire        _buffer_1_auto_out_a_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
  wire [2:0]  _buffer_1_auto_out_a_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
  wire [2:0]  _buffer_1_auto_out_a_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
  wire [2:0]  _buffer_1_auto_out_a_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
  wire [3:0]  _buffer_1_auto_out_a_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
  wire [30:0] _buffer_1_auto_out_a_bits_address;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
  wire [7:0]  _buffer_1_auto_out_a_bits_mask;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
  wire [63:0] _buffer_1_auto_out_a_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
  wire        _buffer_1_auto_out_a_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
  wire        _buffer_1_auto_out_d_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
  wire        _serdesser_auto_manager_in_a_ready;	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
  wire        _serdesser_auto_manager_in_d_valid;	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
  wire [2:0]  _serdesser_auto_manager_in_d_bits_opcode;	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
  wire [1:0]  _serdesser_auto_manager_in_d_bits_param;	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
  wire [2:0]  _serdesser_auto_manager_in_d_bits_size;	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
  wire [3:0]  _serdesser_auto_manager_in_d_bits_source;	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
  wire        _serdesser_auto_manager_in_d_bits_sink;	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
  wire        _serdesser_auto_manager_in_d_bits_denied;	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
  wire [63:0] _serdesser_auto_manager_in_d_bits_data;	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
  wire        _serdesser_auto_manager_in_d_bits_corrupt;	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
  wire        _serdesser_auto_client_out_a_valid;	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
  wire [2:0]  _serdesser_auto_client_out_a_bits_opcode;	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
  wire [2:0]  _serdesser_auto_client_out_a_bits_param;	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
  wire [2:0]  _serdesser_auto_client_out_a_bits_size;	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
  wire [3:0]  _serdesser_auto_client_out_a_bits_source;	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
  wire [31:0] _serdesser_auto_client_out_a_bits_address;	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
  wire [7:0]  _serdesser_auto_client_out_a_bits_mask;	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
  wire [63:0] _serdesser_auto_client_out_a_bits_data;	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
  wire        _serdesser_auto_client_out_a_bits_corrupt;	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
  wire        _serdesser_auto_client_out_d_ready;	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
  wire        _serdesser_io_ser_in_ready;	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
  wire        _serdesser_io_ser_out_valid;	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
  wire [3:0]  _serdesser_io_ser_out_bits;	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
  wire        _tsi2tl_auto_out_a_valid;	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:35:36]
  wire [2:0]  _tsi2tl_auto_out_a_bits_opcode;	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:35:36]
  wire [2:0]  _tsi2tl_auto_out_a_bits_size;	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:35:36]
  wire [31:0] _tsi2tl_auto_out_a_bits_address;	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:35:36]
  wire [7:0]  _tsi2tl_auto_out_a_bits_mask;	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:35:36]
  wire [63:0] _tsi2tl_auto_out_a_bits_data;	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:35:36]
  wire        _tsi2tl_auto_out_d_ready;	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:35:36]
  wire        _tsi2tl_io_tsi_in_ready;	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:35:36]
  wire        _tsi2tl_io_tsi_out_valid;	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:35:36]
  wire [31:0] _tsi2tl_io_tsi_out_bits;	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:35:36]
  wire        _buffer_auto_in_a_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
  wire        _buffer_auto_in_d_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
  wire [2:0]  _buffer_auto_in_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
  wire [1:0]  _buffer_auto_in_d_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
  wire [2:0]  _buffer_auto_in_d_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
  wire [4:0]  _buffer_auto_in_d_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
  wire [1:0]  _buffer_auto_in_d_bits_sink;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
  wire        _buffer_auto_in_d_bits_denied;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
  wire [63:0] _buffer_auto_in_d_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
  wire        _buffer_auto_in_d_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
  wire        _subsystem_fbus_xbar_auto_in_1_a_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
  wire        _subsystem_fbus_xbar_auto_in_1_d_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
  wire [2:0]  _subsystem_fbus_xbar_auto_in_1_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
  wire [1:0]  _subsystem_fbus_xbar_auto_in_1_d_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
  wire [2:0]  _subsystem_fbus_xbar_auto_in_1_d_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
  wire [3:0]  _subsystem_fbus_xbar_auto_in_1_d_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
  wire [1:0]  _subsystem_fbus_xbar_auto_in_1_d_bits_sink;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
  wire        _subsystem_fbus_xbar_auto_in_1_d_bits_denied;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
  wire [63:0] _subsystem_fbus_xbar_auto_in_1_d_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
  wire        _subsystem_fbus_xbar_auto_in_1_d_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
  wire        _subsystem_fbus_xbar_auto_in_0_a_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
  wire        _subsystem_fbus_xbar_auto_in_0_d_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
  wire [63:0] _subsystem_fbus_xbar_auto_in_0_d_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
  wire        _subsystem_fbus_xbar_auto_out_a_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
  wire [2:0]  _subsystem_fbus_xbar_auto_out_a_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
  wire [2:0]  _subsystem_fbus_xbar_auto_out_a_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
  wire [2:0]  _subsystem_fbus_xbar_auto_out_a_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
  wire [4:0]  _subsystem_fbus_xbar_auto_out_a_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
  wire [31:0] _subsystem_fbus_xbar_auto_out_a_bits_address;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
  wire [7:0]  _subsystem_fbus_xbar_auto_out_a_bits_mask;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
  wire [63:0] _subsystem_fbus_xbar_auto_out_a_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
  wire        _subsystem_fbus_xbar_auto_out_a_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
  wire        _subsystem_fbus_xbar_auto_out_d_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
  reg  [1:0]  out_async_io_enq_c_value;	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
  reg         out_async_io_enq_r;	// @[generators/rocket-chip/src/main/scala/util/BlockDuringReset.scala:13:24]
  reg  [1:0]  in_async_io_enq_c_value;	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
  reg         in_async_io_enq_r;	// @[generators/rocket-chip/src/main/scala/util/BlockDuringReset.scala:13:24]
  always @(posedge auto_subsystem_fbus_clock_groups_in_member_subsystem_fbus_0_clock) begin	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
    if (auto_subsystem_fbus_clock_groups_in_member_subsystem_fbus_0_reset) begin	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
      out_async_io_enq_c_value <= 2'h0;	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
      out_async_io_enq_r <= 1'h0;	// @[generators/rocket-chip/src/main/scala/util/BlockDuringReset.scala:13:24]
      in_async_io_enq_c_value <= 2'h0;	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
      in_async_io_enq_r <= 1'h0;	// @[generators/rocket-chip/src/main/scala/util/BlockDuringReset.scala:13:24]
    end
    else begin	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
      out_async_io_enq_c_value <= out_async_io_enq_c_value + 2'h1;	// @[src/main/scala/chisel3/util/Counter.scala:61:40, :77:24]
      out_async_io_enq_r <= (&out_async_io_enq_c_value) | out_async_io_enq_r;	// @[generators/rocket-chip/src/main/scala/util/BlockDuringReset.scala:13:24, src/main/scala/chisel3/util/Counter.scala:61:40, :73:24]
      in_async_io_enq_c_value <= in_async_io_enq_c_value + 2'h1;	// @[src/main/scala/chisel3/util/Counter.scala:61:40, :77:24]
      in_async_io_enq_r <= (&in_async_io_enq_c_value) | in_async_io_enq_r;	// @[generators/rocket-chip/src/main/scala/util/BlockDuringReset.scala:13:24, src/main/scala/chisel3/util/Counter.scala:61:40, :73:24]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;
        out_async_io_enq_c_value = _RANDOM[/*Zero width*/ 1'b0][1:0];	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
        out_async_io_enq_r = _RANDOM[/*Zero width*/ 1'b0][2];	// @[generators/rocket-chip/src/main/scala/util/BlockDuringReset.scala:13:24, src/main/scala/chisel3/util/Counter.scala:61:40]
        in_async_io_enq_c_value = _RANDOM[/*Zero width*/ 1'b0][4:3];	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
        in_async_io_enq_r = _RANDOM[/*Zero width*/ 1'b0][5];	// @[generators/rocket-chip/src/main/scala/util/BlockDuringReset.scala:13:24, src/main/scala/chisel3/util/Counter.scala:61:40]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  TLXbar_3 subsystem_fbus_xbar (	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
    .clock                    (auto_subsystem_fbus_clock_groups_in_member_subsystem_fbus_0_clock),
    .reset                    (auto_subsystem_fbus_clock_groups_in_member_subsystem_fbus_0_reset),
    .auto_in_1_a_ready        (_subsystem_fbus_xbar_auto_in_1_a_ready),
    .auto_in_1_a_valid        (_coupler_from_port_named_serial_tl_ctrl_auto_tl_out_a_valid),	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
    .auto_in_1_a_bits_opcode  (_coupler_from_port_named_serial_tl_ctrl_auto_tl_out_a_bits_opcode),	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
    .auto_in_1_a_bits_param   (_coupler_from_port_named_serial_tl_ctrl_auto_tl_out_a_bits_param),	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
    .auto_in_1_a_bits_size    (_coupler_from_port_named_serial_tl_ctrl_auto_tl_out_a_bits_size),	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
    .auto_in_1_a_bits_source  (_coupler_from_port_named_serial_tl_ctrl_auto_tl_out_a_bits_source),	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
    .auto_in_1_a_bits_address (_coupler_from_port_named_serial_tl_ctrl_auto_tl_out_a_bits_address),	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
    .auto_in_1_a_bits_mask    (_coupler_from_port_named_serial_tl_ctrl_auto_tl_out_a_bits_mask),	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
    .auto_in_1_a_bits_data    (_coupler_from_port_named_serial_tl_ctrl_auto_tl_out_a_bits_data),	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
    .auto_in_1_a_bits_corrupt (_coupler_from_port_named_serial_tl_ctrl_auto_tl_out_a_bits_corrupt),	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
    .auto_in_1_d_ready        (_coupler_from_port_named_serial_tl_ctrl_auto_tl_out_d_ready),	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
    .auto_in_1_d_valid        (_subsystem_fbus_xbar_auto_in_1_d_valid),
    .auto_in_1_d_bits_opcode  (_subsystem_fbus_xbar_auto_in_1_d_bits_opcode),
    .auto_in_1_d_bits_param   (_subsystem_fbus_xbar_auto_in_1_d_bits_param),
    .auto_in_1_d_bits_size    (_subsystem_fbus_xbar_auto_in_1_d_bits_size),
    .auto_in_1_d_bits_source  (_subsystem_fbus_xbar_auto_in_1_d_bits_source),
    .auto_in_1_d_bits_sink    (_subsystem_fbus_xbar_auto_in_1_d_bits_sink),
    .auto_in_1_d_bits_denied  (_subsystem_fbus_xbar_auto_in_1_d_bits_denied),
    .auto_in_1_d_bits_data    (_subsystem_fbus_xbar_auto_in_1_d_bits_data),
    .auto_in_1_d_bits_corrupt (_subsystem_fbus_xbar_auto_in_1_d_bits_corrupt),
    .auto_in_0_a_ready        (_subsystem_fbus_xbar_auto_in_0_a_ready),
    .auto_in_0_a_valid        (_tsi2tl_auto_out_a_valid),	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:35:36]
    .auto_in_0_a_bits_opcode  (_tsi2tl_auto_out_a_bits_opcode),	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:35:36]
    .auto_in_0_a_bits_size    (_tsi2tl_auto_out_a_bits_size),	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:35:36]
    .auto_in_0_a_bits_address (_tsi2tl_auto_out_a_bits_address),	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:35:36]
    .auto_in_0_a_bits_mask    (_tsi2tl_auto_out_a_bits_mask),	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:35:36]
    .auto_in_0_a_bits_data    (_tsi2tl_auto_out_a_bits_data),	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:35:36]
    .auto_in_0_d_ready        (_tsi2tl_auto_out_d_ready),	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:35:36]
    .auto_in_0_d_valid        (_subsystem_fbus_xbar_auto_in_0_d_valid),
    .auto_in_0_d_bits_data    (_subsystem_fbus_xbar_auto_in_0_d_bits_data),
    .auto_out_a_ready         (_buffer_auto_in_a_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
    .auto_out_a_valid         (_subsystem_fbus_xbar_auto_out_a_valid),
    .auto_out_a_bits_opcode   (_subsystem_fbus_xbar_auto_out_a_bits_opcode),
    .auto_out_a_bits_param    (_subsystem_fbus_xbar_auto_out_a_bits_param),
    .auto_out_a_bits_size     (_subsystem_fbus_xbar_auto_out_a_bits_size),
    .auto_out_a_bits_source   (_subsystem_fbus_xbar_auto_out_a_bits_source),
    .auto_out_a_bits_address  (_subsystem_fbus_xbar_auto_out_a_bits_address),
    .auto_out_a_bits_mask     (_subsystem_fbus_xbar_auto_out_a_bits_mask),
    .auto_out_a_bits_data     (_subsystem_fbus_xbar_auto_out_a_bits_data),
    .auto_out_a_bits_corrupt  (_subsystem_fbus_xbar_auto_out_a_bits_corrupt),
    .auto_out_d_ready         (_subsystem_fbus_xbar_auto_out_d_ready),
    .auto_out_d_valid         (_buffer_auto_in_d_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
    .auto_out_d_bits_opcode   (_buffer_auto_in_d_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
    .auto_out_d_bits_param    (_buffer_auto_in_d_bits_param),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
    .auto_out_d_bits_size     (_buffer_auto_in_d_bits_size),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
    .auto_out_d_bits_source   (_buffer_auto_in_d_bits_source),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
    .auto_out_d_bits_sink     (_buffer_auto_in_d_bits_sink),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
    .auto_out_d_bits_denied   (_buffer_auto_in_d_bits_denied),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
    .auto_out_d_bits_data     (_buffer_auto_in_d_bits_data),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
    .auto_out_d_bits_corrupt  (_buffer_auto_in_d_bits_corrupt)	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
  );
  TLBuffer_3 buffer (	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
    .clock                   (auto_subsystem_fbus_clock_groups_in_member_subsystem_fbus_0_clock),
    .reset                   (auto_subsystem_fbus_clock_groups_in_member_subsystem_fbus_0_reset),
    .auto_in_a_ready         (_buffer_auto_in_a_ready),
    .auto_in_a_valid         (_subsystem_fbus_xbar_auto_out_a_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
    .auto_in_a_bits_opcode   (_subsystem_fbus_xbar_auto_out_a_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
    .auto_in_a_bits_param    (_subsystem_fbus_xbar_auto_out_a_bits_param),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
    .auto_in_a_bits_size     (_subsystem_fbus_xbar_auto_out_a_bits_size),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
    .auto_in_a_bits_source   (_subsystem_fbus_xbar_auto_out_a_bits_source),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
    .auto_in_a_bits_address  (_subsystem_fbus_xbar_auto_out_a_bits_address),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
    .auto_in_a_bits_mask     (_subsystem_fbus_xbar_auto_out_a_bits_mask),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
    .auto_in_a_bits_data     (_subsystem_fbus_xbar_auto_out_a_bits_data),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
    .auto_in_a_bits_corrupt  (_subsystem_fbus_xbar_auto_out_a_bits_corrupt),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
    .auto_in_d_ready         (_subsystem_fbus_xbar_auto_out_d_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
    .auto_in_d_valid         (_buffer_auto_in_d_valid),
    .auto_in_d_bits_opcode   (_buffer_auto_in_d_bits_opcode),
    .auto_in_d_bits_param    (_buffer_auto_in_d_bits_param),
    .auto_in_d_bits_size     (_buffer_auto_in_d_bits_size),
    .auto_in_d_bits_source   (_buffer_auto_in_d_bits_source),
    .auto_in_d_bits_sink     (_buffer_auto_in_d_bits_sink),
    .auto_in_d_bits_denied   (_buffer_auto_in_d_bits_denied),
    .auto_in_d_bits_data     (_buffer_auto_in_d_bits_data),
    .auto_in_d_bits_corrupt  (_buffer_auto_in_d_bits_corrupt),
    .auto_out_a_ready        (auto_bus_xing_out_a_ready),
    .auto_out_a_valid        (auto_bus_xing_out_a_valid),
    .auto_out_a_bits_opcode  (auto_bus_xing_out_a_bits_opcode),
    .auto_out_a_bits_param   (auto_bus_xing_out_a_bits_param),
    .auto_out_a_bits_size    (auto_bus_xing_out_a_bits_size),
    .auto_out_a_bits_source  (auto_bus_xing_out_a_bits_source),
    .auto_out_a_bits_address (auto_bus_xing_out_a_bits_address),
    .auto_out_a_bits_mask    (auto_bus_xing_out_a_bits_mask),
    .auto_out_a_bits_data    (auto_bus_xing_out_a_bits_data),
    .auto_out_a_bits_corrupt (auto_bus_xing_out_a_bits_corrupt),
    .auto_out_d_ready        (auto_bus_xing_out_d_ready),
    .auto_out_d_valid        (auto_bus_xing_out_d_valid),
    .auto_out_d_bits_opcode  (auto_bus_xing_out_d_bits_opcode),
    .auto_out_d_bits_param   (auto_bus_xing_out_d_bits_param),
    .auto_out_d_bits_size    (auto_bus_xing_out_d_bits_size),
    .auto_out_d_bits_source  (auto_bus_xing_out_d_bits_source),
    .auto_out_d_bits_sink    (auto_bus_xing_out_d_bits_sink),
    .auto_out_d_bits_denied  (auto_bus_xing_out_d_bits_denied),
    .auto_out_d_bits_data    (auto_bus_xing_out_d_bits_data),
    .auto_out_d_bits_corrupt (auto_bus_xing_out_d_bits_corrupt)
  );
  TSIToTileLink tsi2tl (	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:35:36]
    .clock                   (auto_subsystem_fbus_clock_groups_in_member_subsystem_fbus_0_clock),
    .reset                   (auto_subsystem_fbus_clock_groups_in_member_subsystem_fbus_0_reset),
    .auto_out_a_ready        (_subsystem_fbus_xbar_auto_in_0_a_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
    .auto_out_a_valid        (_tsi2tl_auto_out_a_valid),
    .auto_out_a_bits_opcode  (_tsi2tl_auto_out_a_bits_opcode),
    .auto_out_a_bits_size    (_tsi2tl_auto_out_a_bits_size),
    .auto_out_a_bits_address (_tsi2tl_auto_out_a_bits_address),
    .auto_out_a_bits_mask    (_tsi2tl_auto_out_a_bits_mask),
    .auto_out_a_bits_data    (_tsi2tl_auto_out_a_bits_data),
    .auto_out_d_ready        (_tsi2tl_auto_out_d_ready),
    .auto_out_d_valid        (_subsystem_fbus_xbar_auto_in_0_d_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
    .auto_out_d_bits_data    (_subsystem_fbus_xbar_auto_in_0_d_bits_data),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
    .io_tsi_in_ready         (_tsi2tl_io_tsi_in_ready),
    .io_tsi_in_valid         (_width_adapter_io_wide_out_valid),	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:39:33]
    .io_tsi_in_bits          (_width_adapter_io_wide_out_bits),	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:39:33]
    .io_tsi_out_ready        (_width_adapter_io_wide_in_ready),	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:39:33]
    .io_tsi_out_valid        (_tsi2tl_io_tsi_out_valid),
    .io_tsi_out_bits         (_tsi2tl_io_tsi_out_bits),
    .io_state                (uart_tsi_io_tsi2tl_state)
  );
  TLSerdesser serdesser (	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
    .clock                          (auto_subsystem_fbus_clock_groups_in_member_subsystem_fbus_0_clock),
    .reset                          (auto_subsystem_fbus_clock_groups_in_member_subsystem_fbus_0_reset),
    .auto_manager_in_a_ready        (_serdesser_auto_manager_in_a_ready),
    .auto_manager_in_a_valid        (_buffer_1_auto_out_a_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
    .auto_manager_in_a_bits_opcode  (_buffer_1_auto_out_a_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
    .auto_manager_in_a_bits_param   (_buffer_1_auto_out_a_bits_param),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
    .auto_manager_in_a_bits_size    (_buffer_1_auto_out_a_bits_size),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
    .auto_manager_in_a_bits_source  (_buffer_1_auto_out_a_bits_source),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
    .auto_manager_in_a_bits_address (_buffer_1_auto_out_a_bits_address),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
    .auto_manager_in_a_bits_mask    (_buffer_1_auto_out_a_bits_mask),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
    .auto_manager_in_a_bits_data    (_buffer_1_auto_out_a_bits_data),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
    .auto_manager_in_a_bits_corrupt (_buffer_1_auto_out_a_bits_corrupt),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
    .auto_manager_in_d_ready        (_buffer_1_auto_out_d_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
    .auto_manager_in_d_valid        (_serdesser_auto_manager_in_d_valid),
    .auto_manager_in_d_bits_opcode  (_serdesser_auto_manager_in_d_bits_opcode),
    .auto_manager_in_d_bits_param   (_serdesser_auto_manager_in_d_bits_param),
    .auto_manager_in_d_bits_size    (_serdesser_auto_manager_in_d_bits_size),
    .auto_manager_in_d_bits_source  (_serdesser_auto_manager_in_d_bits_source),
    .auto_manager_in_d_bits_sink    (_serdesser_auto_manager_in_d_bits_sink),
    .auto_manager_in_d_bits_denied  (_serdesser_auto_manager_in_d_bits_denied),
    .auto_manager_in_d_bits_data    (_serdesser_auto_manager_in_d_bits_data),
    .auto_manager_in_d_bits_corrupt (_serdesser_auto_manager_in_d_bits_corrupt),
    .auto_client_out_a_ready        (_coupler_from_port_named_serial_tl_ctrl_auto_buffer_in_a_ready),	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
    .auto_client_out_a_valid        (_serdesser_auto_client_out_a_valid),
    .auto_client_out_a_bits_opcode  (_serdesser_auto_client_out_a_bits_opcode),
    .auto_client_out_a_bits_param   (_serdesser_auto_client_out_a_bits_param),
    .auto_client_out_a_bits_size    (_serdesser_auto_client_out_a_bits_size),
    .auto_client_out_a_bits_source  (_serdesser_auto_client_out_a_bits_source),
    .auto_client_out_a_bits_address (_serdesser_auto_client_out_a_bits_address),
    .auto_client_out_a_bits_mask    (_serdesser_auto_client_out_a_bits_mask),
    .auto_client_out_a_bits_data    (_serdesser_auto_client_out_a_bits_data),
    .auto_client_out_a_bits_corrupt (_serdesser_auto_client_out_a_bits_corrupt),
    .auto_client_out_d_ready        (_serdesser_auto_client_out_d_ready),
    .auto_client_out_d_valid        (_coupler_from_port_named_serial_tl_ctrl_auto_buffer_in_d_valid),	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
    .auto_client_out_d_bits_opcode  (_coupler_from_port_named_serial_tl_ctrl_auto_buffer_in_d_bits_opcode),	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
    .auto_client_out_d_bits_param   (_coupler_from_port_named_serial_tl_ctrl_auto_buffer_in_d_bits_param),	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
    .auto_client_out_d_bits_size    (_coupler_from_port_named_serial_tl_ctrl_auto_buffer_in_d_bits_size),	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
    .auto_client_out_d_bits_source  (_coupler_from_port_named_serial_tl_ctrl_auto_buffer_in_d_bits_source),	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
    .auto_client_out_d_bits_sink    (_coupler_from_port_named_serial_tl_ctrl_auto_buffer_in_d_bits_sink),	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
    .auto_client_out_d_bits_denied  (_coupler_from_port_named_serial_tl_ctrl_auto_buffer_in_d_bits_denied),	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
    .auto_client_out_d_bits_data    (_coupler_from_port_named_serial_tl_ctrl_auto_buffer_in_d_bits_data),	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
    .auto_client_out_d_bits_corrupt (_coupler_from_port_named_serial_tl_ctrl_auto_buffer_in_d_bits_corrupt),	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
    .io_ser_in_ready                (_serdesser_io_ser_in_ready),
    .io_ser_in_valid                (_in_async_io_deq_valid),	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:133:28]
    .io_ser_in_bits                 (_in_async_io_deq_bits),	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:133:28]
    .io_ser_out_ready               (out_async_io_enq_r & _out_async_io_enq_ready),	// @[generators/rocket-chip/src/main/scala/util/BlockDuringReset.scala:13:24, generators/rocket-chip/src/main/scala/util/Blockable.scala:35:18, :37:30, :39:20, generators/testchipip/src/main/scala/PeripheryTLSerial.scala:126:29]
    .io_ser_out_valid               (_serdesser_io_ser_out_valid),
    .io_ser_out_bits                (_serdesser_io_ser_out_bits)
  );
  TLBuffer_4 buffer_1 (	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:69:28]
    .clock                   (auto_subsystem_fbus_clock_groups_in_member_subsystem_fbus_0_clock),
    .reset                   (auto_subsystem_fbus_clock_groups_in_member_subsystem_fbus_0_reset),
    .auto_in_a_ready         (auto_tlserial_manager_crossing_in_a_ready),
    .auto_in_a_valid         (auto_tlserial_manager_crossing_in_a_valid),
    .auto_in_a_bits_opcode   (auto_tlserial_manager_crossing_in_a_bits_opcode),
    .auto_in_a_bits_param    (auto_tlserial_manager_crossing_in_a_bits_param),
    .auto_in_a_bits_size     (auto_tlserial_manager_crossing_in_a_bits_size),
    .auto_in_a_bits_source   (auto_tlserial_manager_crossing_in_a_bits_source),
    .auto_in_a_bits_address  (auto_tlserial_manager_crossing_in_a_bits_address),
    .auto_in_a_bits_mask     (auto_tlserial_manager_crossing_in_a_bits_mask),
    .auto_in_a_bits_data     (auto_tlserial_manager_crossing_in_a_bits_data),
    .auto_in_a_bits_corrupt  (auto_tlserial_manager_crossing_in_a_bits_corrupt),
    .auto_in_d_ready         (auto_tlserial_manager_crossing_in_d_ready),
    .auto_in_d_valid         (auto_tlserial_manager_crossing_in_d_valid),
    .auto_in_d_bits_opcode   (auto_tlserial_manager_crossing_in_d_bits_opcode),
    .auto_in_d_bits_param    (auto_tlserial_manager_crossing_in_d_bits_param),
    .auto_in_d_bits_size     (auto_tlserial_manager_crossing_in_d_bits_size),
    .auto_in_d_bits_source   (auto_tlserial_manager_crossing_in_d_bits_source),
    .auto_in_d_bits_sink     (auto_tlserial_manager_crossing_in_d_bits_sink),
    .auto_in_d_bits_denied   (auto_tlserial_manager_crossing_in_d_bits_denied),
    .auto_in_d_bits_data     (auto_tlserial_manager_crossing_in_d_bits_data),
    .auto_in_d_bits_corrupt  (auto_tlserial_manager_crossing_in_d_bits_corrupt),
    .auto_out_a_ready        (_serdesser_auto_manager_in_a_ready),	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
    .auto_out_a_valid        (_buffer_1_auto_out_a_valid),
    .auto_out_a_bits_opcode  (_buffer_1_auto_out_a_bits_opcode),
    .auto_out_a_bits_param   (_buffer_1_auto_out_a_bits_param),
    .auto_out_a_bits_size    (_buffer_1_auto_out_a_bits_size),
    .auto_out_a_bits_source  (_buffer_1_auto_out_a_bits_source),
    .auto_out_a_bits_address (_buffer_1_auto_out_a_bits_address),
    .auto_out_a_bits_mask    (_buffer_1_auto_out_a_bits_mask),
    .auto_out_a_bits_data    (_buffer_1_auto_out_a_bits_data),
    .auto_out_a_bits_corrupt (_buffer_1_auto_out_a_bits_corrupt),
    .auto_out_d_ready        (_buffer_1_auto_out_d_ready),
    .auto_out_d_valid        (_serdesser_auto_manager_in_d_valid),	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
    .auto_out_d_bits_opcode  (_serdesser_auto_manager_in_d_bits_opcode),	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
    .auto_out_d_bits_param   (_serdesser_auto_manager_in_d_bits_param),	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
    .auto_out_d_bits_size    (_serdesser_auto_manager_in_d_bits_size),	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
    .auto_out_d_bits_source  (_serdesser_auto_manager_in_d_bits_source),	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
    .auto_out_d_bits_sink    (_serdesser_auto_manager_in_d_bits_sink),	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
    .auto_out_d_bits_denied  (_serdesser_auto_manager_in_d_bits_denied),	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
    .auto_out_d_bits_data    (_serdesser_auto_manager_in_d_bits_data),	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
    .auto_out_d_bits_corrupt (_serdesser_auto_manager_in_d_bits_corrupt)	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
  );
  TLInterconnectCoupler_5 coupler_from_port_named_serial_tl_ctrl (	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:494:27]
    .clock                         (auto_subsystem_fbus_clock_groups_in_member_subsystem_fbus_0_clock),
    .reset                         (auto_subsystem_fbus_clock_groups_in_member_subsystem_fbus_0_reset),
    .auto_buffer_in_a_ready        (_coupler_from_port_named_serial_tl_ctrl_auto_buffer_in_a_ready),
    .auto_buffer_in_a_valid        (_serdesser_auto_client_out_a_valid),	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
    .auto_buffer_in_a_bits_opcode  (_serdesser_auto_client_out_a_bits_opcode),	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
    .auto_buffer_in_a_bits_param   (_serdesser_auto_client_out_a_bits_param),	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
    .auto_buffer_in_a_bits_size    (_serdesser_auto_client_out_a_bits_size),	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
    .auto_buffer_in_a_bits_source  (_serdesser_auto_client_out_a_bits_source),	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
    .auto_buffer_in_a_bits_address (_serdesser_auto_client_out_a_bits_address),	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
    .auto_buffer_in_a_bits_mask    (_serdesser_auto_client_out_a_bits_mask),	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
    .auto_buffer_in_a_bits_data    (_serdesser_auto_client_out_a_bits_data),	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
    .auto_buffer_in_a_bits_corrupt (_serdesser_auto_client_out_a_bits_corrupt),	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
    .auto_buffer_in_d_ready        (_serdesser_auto_client_out_d_ready),	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
    .auto_buffer_in_d_valid        (_coupler_from_port_named_serial_tl_ctrl_auto_buffer_in_d_valid),
    .auto_buffer_in_d_bits_opcode  (_coupler_from_port_named_serial_tl_ctrl_auto_buffer_in_d_bits_opcode),
    .auto_buffer_in_d_bits_param   (_coupler_from_port_named_serial_tl_ctrl_auto_buffer_in_d_bits_param),
    .auto_buffer_in_d_bits_size    (_coupler_from_port_named_serial_tl_ctrl_auto_buffer_in_d_bits_size),
    .auto_buffer_in_d_bits_source  (_coupler_from_port_named_serial_tl_ctrl_auto_buffer_in_d_bits_source),
    .auto_buffer_in_d_bits_sink    (_coupler_from_port_named_serial_tl_ctrl_auto_buffer_in_d_bits_sink),
    .auto_buffer_in_d_bits_denied  (_coupler_from_port_named_serial_tl_ctrl_auto_buffer_in_d_bits_denied),
    .auto_buffer_in_d_bits_data    (_coupler_from_port_named_serial_tl_ctrl_auto_buffer_in_d_bits_data),
    .auto_buffer_in_d_bits_corrupt (_coupler_from_port_named_serial_tl_ctrl_auto_buffer_in_d_bits_corrupt),
    .auto_tl_out_a_ready           (_subsystem_fbus_xbar_auto_in_1_a_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
    .auto_tl_out_a_valid           (_coupler_from_port_named_serial_tl_ctrl_auto_tl_out_a_valid),
    .auto_tl_out_a_bits_opcode     (_coupler_from_port_named_serial_tl_ctrl_auto_tl_out_a_bits_opcode),
    .auto_tl_out_a_bits_param      (_coupler_from_port_named_serial_tl_ctrl_auto_tl_out_a_bits_param),
    .auto_tl_out_a_bits_size       (_coupler_from_port_named_serial_tl_ctrl_auto_tl_out_a_bits_size),
    .auto_tl_out_a_bits_source     (_coupler_from_port_named_serial_tl_ctrl_auto_tl_out_a_bits_source),
    .auto_tl_out_a_bits_address    (_coupler_from_port_named_serial_tl_ctrl_auto_tl_out_a_bits_address),
    .auto_tl_out_a_bits_mask       (_coupler_from_port_named_serial_tl_ctrl_auto_tl_out_a_bits_mask),
    .auto_tl_out_a_bits_data       (_coupler_from_port_named_serial_tl_ctrl_auto_tl_out_a_bits_data),
    .auto_tl_out_a_bits_corrupt    (_coupler_from_port_named_serial_tl_ctrl_auto_tl_out_a_bits_corrupt),
    .auto_tl_out_d_ready           (_coupler_from_port_named_serial_tl_ctrl_auto_tl_out_d_ready),
    .auto_tl_out_d_valid           (_subsystem_fbus_xbar_auto_in_1_d_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
    .auto_tl_out_d_bits_opcode     (_subsystem_fbus_xbar_auto_in_1_d_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
    .auto_tl_out_d_bits_param      (_subsystem_fbus_xbar_auto_in_1_d_bits_param),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
    .auto_tl_out_d_bits_size       (_subsystem_fbus_xbar_auto_in_1_d_bits_size),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
    .auto_tl_out_d_bits_source     (_subsystem_fbus_xbar_auto_in_1_d_bits_source),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
    .auto_tl_out_d_bits_sink       (_subsystem_fbus_xbar_auto_in_1_d_bits_sink),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
    .auto_tl_out_d_bits_denied     (_subsystem_fbus_xbar_auto_in_1_d_bits_denied),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
    .auto_tl_out_d_bits_data       (_subsystem_fbus_xbar_auto_in_1_d_bits_data),	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
    .auto_tl_out_d_bits_corrupt    (_subsystem_fbus_xbar_auto_in_1_d_bits_corrupt)	// @[generators/rocket-chip/src/main/scala/tilelink/BusWrapper.scala:221:32]
  );
  UARTToSerial uart_to_serial (	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:38:34]
    .clock               (auto_subsystem_fbus_clock_groups_in_member_subsystem_fbus_0_clock),
    .reset               (auto_subsystem_fbus_clock_groups_in_member_subsystem_fbus_0_reset),
    .io_uart_txd         (uart_tsi_io_uart_txd),
    .io_uart_rxd         (uart_tsi_io_uart_rxd),
    .io_serial_in_ready  (_uart_to_serial_io_serial_in_ready),
    .io_serial_in_valid  (_width_adapter_io_narrow_out_valid),	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:39:33]
    .io_serial_in_bits   (_width_adapter_io_narrow_out_bits),	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:39:33]
    .io_serial_out_ready (_width_adapter_io_narrow_in_ready),	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:39:33]
    .io_serial_out_valid (_uart_to_serial_io_serial_out_valid),
    .io_serial_out_bits  (_uart_to_serial_io_serial_out_bits),
    .io_dropped          (uart_tsi_io_dropped)
  );
  SerialWidthAdapter width_adapter (	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:39:33]
    .clock               (auto_subsystem_fbus_clock_groups_in_member_subsystem_fbus_0_clock),
    .reset               (auto_subsystem_fbus_clock_groups_in_member_subsystem_fbus_0_reset),
    .io_narrow_in_ready  (_width_adapter_io_narrow_in_ready),
    .io_narrow_in_valid  (_uart_to_serial_io_serial_out_valid),	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:38:34]
    .io_narrow_in_bits   (_uart_to_serial_io_serial_out_bits),	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:38:34]
    .io_narrow_out_ready (_uart_to_serial_io_serial_in_ready),	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:38:34]
    .io_narrow_out_valid (_width_adapter_io_narrow_out_valid),
    .io_narrow_out_bits  (_width_adapter_io_narrow_out_bits),
    .io_wide_in_ready    (_width_adapter_io_wide_in_ready),
    .io_wide_in_valid    (_tsi2tl_io_tsi_out_valid),	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:35:36]
    .io_wide_in_bits     (_tsi2tl_io_tsi_out_bits),	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:35:36]
    .io_wide_out_ready   (_tsi2tl_io_tsi_in_ready),	// @[generators/testchipip/src/main/scala/PeripheryUARTTSI.scala:35:36]
    .io_wide_out_valid   (_width_adapter_io_wide_out_valid),
    .io_wide_out_bits    (_width_adapter_io_wide_out_bits)
  );
  ResetCatchAndSync_d3 outer_reset_catcher (	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
    .clock         (auto_serial_tl_clock_in_clock),
    .reset         (auto_subsystem_fbus_clock_groups_in_member_subsystem_fbus_0_reset),
    .io_sync_reset (_outer_reset_catcher_io_sync_reset)
  );
  AsyncQueue out_async (	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:126:29]
    .io_enq_clock (auto_subsystem_fbus_clock_groups_in_member_subsystem_fbus_0_clock),
    .io_enq_reset (auto_subsystem_fbus_clock_groups_in_member_subsystem_fbus_0_reset),
    .io_enq_ready (_out_async_io_enq_ready),
    .io_enq_valid (out_async_io_enq_r & _serdesser_io_ser_out_valid),	// @[generators/rocket-chip/src/main/scala/util/BlockDuringReset.scala:13:24, generators/rocket-chip/src/main/scala/util/Blockable.scala:34:18, :37:30, :38:20, generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
    .io_enq_bits  (_serdesser_io_ser_out_bits),	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
    .io_deq_clock (auto_serial_tl_clock_in_clock),
    .io_deq_reset (_outer_reset_catcher_io_sync_reset),	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
    .io_deq_ready (serial_tl_bits_out_ready),
    .io_deq_valid (serial_tl_bits_out_valid),
    .io_deq_bits  (serial_tl_bits_out_bits)
  );
  AsyncQueue in_async (	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:133:28]
    .io_enq_clock (auto_serial_tl_clock_in_clock),
    .io_enq_reset (_outer_reset_catcher_io_sync_reset),	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
    .io_enq_ready (_in_async_io_enq_ready),
    .io_enq_valid (in_async_io_enq_r & serial_tl_bits_in_valid),	// @[generators/rocket-chip/src/main/scala/util/BlockDuringReset.scala:13:24, generators/rocket-chip/src/main/scala/util/Blockable.scala:34:18, :37:30, :38:20]
    .io_enq_bits  (serial_tl_bits_in_bits),
    .io_deq_clock (auto_subsystem_fbus_clock_groups_in_member_subsystem_fbus_0_clock),
    .io_deq_reset (auto_subsystem_fbus_clock_groups_in_member_subsystem_fbus_0_reset),
    .io_deq_ready (_serdesser_io_ser_in_ready),	// @[generators/testchipip/src/main/scala/PeripheryTLSerial.scala:87:40]
    .io_deq_valid (_in_async_io_deq_valid),
    .io_deq_bits  (_in_async_io_deq_bits)
  );
  assign serial_tl_clock = auto_serial_tl_clock_in_clock;
  assign serial_tl_bits_in_ready = in_async_io_enq_r & _in_async_io_enq_ready;	// @[generators/rocket-chip/src/main/scala/util/BlockDuringReset.scala:13:24, generators/rocket-chip/src/main/scala/util/Blockable.scala:35:18, :37:30, :39:20, generators/testchipip/src/main/scala/PeripheryTLSerial.scala:133:28]
endmodule

