// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module NexysVideoHarness(
  input         sys_clock,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  inout         uart_txd,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
                uart_rxd,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output [14:0] ddr_ddr3_addr,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output [2:0]  ddr_ddr3_ba,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output        ddr_ddr3_ras_n,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
                ddr_ddr3_cas_n,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
                ddr_ddr3_we_n,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
                ddr_ddr3_reset_n,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
                ddr_ddr3_ck_p,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
                ddr_ddr3_ck_n,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
                ddr_ddr3_cke,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output [1:0]  ddr_ddr3_dm,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output        ddr_ddr3_odt,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  inout  [15:0] ddr_ddr3_dq,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  inout  [1:0]  ddr_ddr3_dqs_n,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
                ddr_ddr3_dqs_p,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  output        led_0,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
                led_1,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
                led_2,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
                led_3,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
                led_4,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
                led_5,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
                led_6,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
                led_7,	// @[fpga/fpga-shells/src/main/scala/shell/IOShell.scala:149:18]
  input         reset,	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/NexysVideoShell.scala:366:19]
  output        serial_tl_clock,	// @[fpga/src/main/scala/nexysvideo/HarnessBinders.scala:57:23]
                serial_tl_bits_in_ready,	// @[fpga/src/main/scala/nexysvideo/HarnessBinders.scala:57:23]
  input         serial_tl_bits_in_valid,	// @[fpga/src/main/scala/nexysvideo/HarnessBinders.scala:57:23]
  input  [3:0]  serial_tl_bits_in_bits,	// @[fpga/src/main/scala/nexysvideo/HarnessBinders.scala:57:23]
  input         serial_tl_bits_out_ready,	// @[fpga/src/main/scala/nexysvideo/HarnessBinders.scala:57:23]
  output        serial_tl_bits_out_valid,	// @[fpga/src/main/scala/nexysvideo/HarnessBinders.scala:57:23]
  output [3:0]  serial_tl_bits_out_bits,	// @[fpga/src/main/scala/nexysvideo/HarnessBinders.scala:57:23]
  input  [3:0]  fpga_gpio
);
  assign fpga_gpio = {0, 0, 0, 0};

  wire        _harnessBinderReset_catcher_io_sync_reset;	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
  wire        _chiptop0_tl_slave_0_a_valid;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [2:0]  _chiptop0_tl_slave_0_a_bits_opcode;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [2:0]  _chiptop0_tl_slave_0_a_bits_param;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [2:0]  _chiptop0_tl_slave_0_a_bits_size;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [3:0]  _chiptop0_tl_slave_0_a_bits_source;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [31:0] _chiptop0_tl_slave_0_a_bits_address;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [7:0]  _chiptop0_tl_slave_0_a_bits_mask;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [63:0] _chiptop0_tl_slave_0_a_bits_data;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_tl_slave_0_a_bits_corrupt;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_tl_slave_0_d_ready;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _chiptop0_uart_tsi_uart_txd;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire [3:0]  _chiptop0_uart_tsi_tsi2tl_state;	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  wire        _powerOnReset_fpga_power_on_power_on_reset;	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Xilinx.scala:103:21]
  wire        _reset_ibuf_O;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/NexysVideoShell.scala:369:28]
  wire        _io_uart_bbIn_rxd_a2b_b;	// @[fpga/fpga-shells/src/main/scala/shell/Util.scala:29:21]
  wire        _sys_clock_ibufg_O;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ClockOverlay.scala:32:22]
  wire        _harnessSysPLLNode_clk_out1;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/XilinxShell.scala:76:55]
  wire        _harnessSysPLLNode_clk_out2;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/XilinxShell.scala:76:55]
  wire        _harnessSysPLLNode_clk_out3;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/XilinxShell.scala:76:55]
  wire        _harnessSysPLLNode_locked;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/XilinxShell.scala:76:55]
  wire        _mig_auto_buffer_in_a_ready;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/NexysVideoShell.scala:283:23]
  wire        _mig_auto_buffer_in_d_valid;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/NexysVideoShell.scala:283:23]
  wire [2:0]  _mig_auto_buffer_in_d_bits_opcode;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/NexysVideoShell.scala:283:23]
  wire [1:0]  _mig_auto_buffer_in_d_bits_param;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/NexysVideoShell.scala:283:23]
  wire [2:0]  _mig_auto_buffer_in_d_bits_size;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/NexysVideoShell.scala:283:23]
  wire [3:0]  _mig_auto_buffer_in_d_bits_source;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/NexysVideoShell.scala:283:23]
  wire        _mig_auto_buffer_in_d_bits_sink;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/NexysVideoShell.scala:283:23]
  wire        _mig_auto_buffer_in_d_bits_denied;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/NexysVideoShell.scala:283:23]
  wire [63:0] _mig_auto_buffer_in_d_bits_data;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/NexysVideoShell.scala:283:23]
  wire        _mig_auto_buffer_in_d_bits_corrupt;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/NexysVideoShell.scala:283:23]
  wire        _mig_io_port_ui_clk;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/NexysVideoShell.scala:283:23]
  wire        _mig_io_port_ui_clk_sync_rst;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/NexysVideoShell.scala:283:23]
  wire        _mig_io_port_mmcm_locked;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/NexysVideoShell.scala:283:23]
  wire        _mig_io_port_init_calib_complete;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/NexysVideoShell.scala:283:23]
  wire        _ddrGroup_auto_out_1_clock;	// @[fpga/fpga-shells/src/main/scala/clocks/ClockGroup.scala:29:15]
  wire        _ddrGroup_auto_out_1_reset;	// @[fpga/fpga-shells/src/main/scala/clocks/ClockGroup.scala:29:15]
  wire        _ddrGroup_auto_out_0_clock;	// @[fpga/fpga-shells/src/main/scala/clocks/ClockGroup.scala:29:15]
  wire        _ddrGroup_auto_out_0_reset;	// @[fpga/fpga-shells/src/main/scala/clocks/ClockGroup.scala:29:15]
  wire        _dutGroup_auto_out_clock;	// @[fpga/fpga-shells/src/main/scala/clocks/ClockGroup.scala:29:15]
  wire        _dutGroup_auto_out_reset;	// @[fpga/fpga-shells/src/main/scala/clocks/ClockGroup.scala:29:15]
  wire        _dutWrangler_auto_out_3_reset;	// @[fpga/src/main/scala/nexysvideo/Harness.scala:29:31]
  wire        _dutWrangler_auto_out_2_clock;	// @[fpga/src/main/scala/nexysvideo/Harness.scala:29:31]
  wire        _dutWrangler_auto_out_1_clock;	// @[fpga/src/main/scala/nexysvideo/Harness.scala:29:31]
  wire        _dutWrangler_auto_out_0_clock;	// @[fpga/src/main/scala/nexysvideo/Harness.scala:29:31]
  wire        _dutWrangler_auto_out_0_reset;	// @[fpga/src/main/scala/nexysvideo/Harness.scala:29:31]
  reg  [1:0]  ddrBlockDuringReset_nodeOut_a_c_value;	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
  reg         ddrBlockDuringReset_nodeOut_a_r;	// @[generators/rocket-chip/src/main/scala/util/BlockDuringReset.scala:13:24]
  reg  [1:0]  ddrBlockDuringReset_nodeIn_d_c_value;	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
  reg         ddrBlockDuringReset_nodeIn_d_r;	// @[generators/rocket-chip/src/main/scala/util/BlockDuringReset.scala:13:24]
  wire        _GEN = ~_reset_ibuf_O | _powerOnReset_fpga_power_on_power_on_reset;	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Xilinx.scala:103:21, fpga/fpga-shells/src/main/scala/shell/xilinx/NexysVideoShell.scala:369:28, :379:{18,36}]
  reg  [25:0] REG;	// @[fpga/src/main/scala/nexysvideo/Harness.scala:64:28]
  reg         REG_1;	// @[fpga/src/main/scala/nexysvideo/Harness.scala:65:23]
  always @(posedge _dutWrangler_auto_out_0_clock) begin	// @[fpga/src/main/scala/nexysvideo/Harness.scala:29:31]
    if (_harnessBinderReset_catcher_io_sync_reset | ~_mig_io_port_init_calib_complete) begin	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/NexysVideoShell.scala:283:23, fpga/src/main/scala/nexysvideo/Harness.scala:29:31, :86:{73,76}, generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
      ddrBlockDuringReset_nodeOut_a_c_value <= 2'h0;	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
      ddrBlockDuringReset_nodeOut_a_r <= 1'h0;	// @[generators/rocket-chip/src/main/scala/util/BlockDuringReset.scala:13:24]
      ddrBlockDuringReset_nodeIn_d_c_value <= 2'h0;	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
      ddrBlockDuringReset_nodeIn_d_r <= 1'h0;	// @[generators/rocket-chip/src/main/scala/util/BlockDuringReset.scala:13:24]
    end
    else begin	// @[fpga/src/main/scala/nexysvideo/Harness.scala:29:31]
      ddrBlockDuringReset_nodeOut_a_c_value <= ddrBlockDuringReset_nodeOut_a_c_value + 2'h1;	// @[src/main/scala/chisel3/util/Counter.scala:61:40, :77:24]
      ddrBlockDuringReset_nodeOut_a_r <= (&ddrBlockDuringReset_nodeOut_a_c_value) | ddrBlockDuringReset_nodeOut_a_r;	// @[generators/rocket-chip/src/main/scala/util/BlockDuringReset.scala:13:24, src/main/scala/chisel3/util/Counter.scala:61:40, :73:24]
      ddrBlockDuringReset_nodeIn_d_c_value <= ddrBlockDuringReset_nodeIn_d_c_value + 2'h1;	// @[src/main/scala/chisel3/util/Counter.scala:61:40, :77:24]
      ddrBlockDuringReset_nodeIn_d_r <= (&ddrBlockDuringReset_nodeIn_d_c_value) | ddrBlockDuringReset_nodeIn_d_r;	// @[generators/rocket-chip/src/main/scala/util/BlockDuringReset.scala:13:24, src/main/scala/chisel3/util/Counter.scala:61:40, :73:24]
    end
  end // always @(posedge)
  always @(posedge _sys_clock_ibufg_O) begin	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ClockOverlay.scala:32:22]
    if (_dutWrangler_auto_out_0_reset) begin	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ClockOverlay.scala:32:22, fpga/src/main/scala/nexysvideo/Harness.scala:29:31]
      REG <= 26'h0;	// @[fpga/src/main/scala/nexysvideo/Harness.scala:64:28]
      REG_1 <= 1'h0;	// @[fpga/src/main/scala/nexysvideo/Harness.scala:65:23]
    end
    else begin	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ClockOverlay.scala:32:22]
      if (REG == 26'h31FFFFF)	// @[fpga/src/main/scala/nexysvideo/Harness.scala:64:28, :67:30]
        REG <= 26'h0;	// @[fpga/src/main/scala/nexysvideo/Harness.scala:64:28]
      else	// @[fpga/src/main/scala/nexysvideo/Harness.scala:67:30]
        REG <= REG + 26'h1;	// @[fpga/src/main/scala/nexysvideo/Harness.scala:64:28, :67:61]
      if (REG == 26'h0)	// @[fpga/src/main/scala/nexysvideo/Harness.scala:64:28, :68:21]
        REG_1 <= ~REG_1 & REG_1 - 1'h1;	// @[fpga/src/main/scala/nexysvideo/Harness.scala:65:23, :69:{18,58}]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:1];
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;
        end
        ddrBlockDuringReset_nodeOut_a_c_value = _RANDOM[1'h0][1:0];	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
        ddrBlockDuringReset_nodeOut_a_r = _RANDOM[1'h0][2];	// @[generators/rocket-chip/src/main/scala/util/BlockDuringReset.scala:13:24, src/main/scala/chisel3/util/Counter.scala:61:40]
        ddrBlockDuringReset_nodeIn_d_c_value = _RANDOM[1'h0][4:3];	// @[src/main/scala/chisel3/util/Counter.scala:61:40]
        ddrBlockDuringReset_nodeIn_d_r = _RANDOM[1'h0][5];	// @[generators/rocket-chip/src/main/scala/util/BlockDuringReset.scala:13:24, src/main/scala/chisel3/util/Counter.scala:61:40]
        REG = _RANDOM[1'h0][31:6];	// @[fpga/src/main/scala/nexysvideo/Harness.scala:64:28, src/main/scala/chisel3/util/Counter.scala:61:40]
        REG_1 = _RANDOM[1'h1][0];	// @[fpga/src/main/scala/nexysvideo/Harness.scala:65:23]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  ResetWrangler dutWrangler (	// @[fpga/src/main/scala/nexysvideo/Harness.scala:29:31]
    .auto_in_3_clock  (_mig_io_port_ui_clk),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/NexysVideoShell.scala:283:23]
    .auto_in_3_reset  (~_mig_io_port_mmcm_locked | _mig_io_port_ui_clk_sync_rst),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/NexysVideoShell.scala:283:23, :302:{17,35}]
    .auto_in_2_clock  (_ddrGroup_auto_out_1_clock),	// @[fpga/fpga-shells/src/main/scala/clocks/ClockGroup.scala:29:15]
    .auto_in_2_reset  (_ddrGroup_auto_out_1_reset),	// @[fpga/fpga-shells/src/main/scala/clocks/ClockGroup.scala:29:15]
    .auto_in_1_clock  (_ddrGroup_auto_out_0_clock),	// @[fpga/fpga-shells/src/main/scala/clocks/ClockGroup.scala:29:15]
    .auto_in_1_reset  (_ddrGroup_auto_out_0_reset),	// @[fpga/fpga-shells/src/main/scala/clocks/ClockGroup.scala:29:15]
    .auto_in_0_clock  (_dutGroup_auto_out_clock),	// @[fpga/fpga-shells/src/main/scala/clocks/ClockGroup.scala:29:15]
    .auto_in_0_reset  (_dutGroup_auto_out_reset),	// @[fpga/fpga-shells/src/main/scala/clocks/ClockGroup.scala:29:15]
    .auto_out_3_reset (_dutWrangler_auto_out_3_reset),
    .auto_out_2_clock (_dutWrangler_auto_out_2_clock),
    .auto_out_1_clock (_dutWrangler_auto_out_1_clock),
    .auto_out_0_clock (_dutWrangler_auto_out_0_clock),
    .auto_out_0_reset (_dutWrangler_auto_out_0_reset)
  );
  ClockGroup dutGroup (	// @[fpga/fpga-shells/src/main/scala/clocks/ClockGroup.scala:29:15]
    .auto_in_member_0_clock (_harnessSysPLLNode_clk_out1),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/XilinxShell.scala:76:55]
    .auto_in_member_0_reset (~_harnessSysPLLNode_locked | ~_reset_ibuf_O),	// @[fpga/fpga-shells/src/main/scala/clocks/PLLFactory.scala:77:{20,35}, fpga/fpga-shells/src/main/scala/shell/xilinx/NexysVideoShell.scala:369:28, fpga/fpga-shells/src/main/scala/shell/xilinx/XilinxShell.scala:76:55, fpga/src/main/scala/nexysvideo/Harness.scala:57:56]
    .auto_out_clock         (_dutGroup_auto_out_clock),
    .auto_out_reset         (_dutGroup_auto_out_reset)
  );
  ClockGroup_1 ddrGroup (	// @[fpga/fpga-shells/src/main/scala/clocks/ClockGroup.scala:29:15]
    .auto_in_member_1_clock (_harnessSysPLLNode_clk_out3),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/XilinxShell.scala:76:55]
    .auto_in_member_1_reset (~_harnessSysPLLNode_locked | ~_reset_ibuf_O),	// @[fpga/fpga-shells/src/main/scala/clocks/PLLFactory.scala:77:{20,35}, fpga/fpga-shells/src/main/scala/shell/xilinx/NexysVideoShell.scala:369:28, fpga/fpga-shells/src/main/scala/shell/xilinx/XilinxShell.scala:76:55, fpga/src/main/scala/nexysvideo/Harness.scala:57:56]
    .auto_in_member_0_clock (_harnessSysPLLNode_clk_out2),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/XilinxShell.scala:76:55]
    .auto_in_member_0_reset (~_harnessSysPLLNode_locked | ~_reset_ibuf_O),	// @[fpga/fpga-shells/src/main/scala/clocks/PLLFactory.scala:77:{20,35}, fpga/fpga-shells/src/main/scala/shell/xilinx/NexysVideoShell.scala:369:28, fpga/fpga-shells/src/main/scala/shell/xilinx/XilinxShell.scala:76:55, fpga/src/main/scala/nexysvideo/Harness.scala:57:56]
    .auto_out_1_clock       (_ddrGroup_auto_out_1_clock),
    .auto_out_1_reset       (_ddrGroup_auto_out_1_reset),
    .auto_out_0_clock       (_ddrGroup_auto_out_0_clock),
    .auto_out_0_reset       (_ddrGroup_auto_out_0_reset)
  );
  XilinxNexysVideoMIG mig (	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/NexysVideoShell.scala:283:23]
    .clock                         (_dutWrangler_auto_out_0_clock),	// @[fpga/src/main/scala/nexysvideo/Harness.scala:29:31]
    .reset                         (_harnessBinderReset_catcher_io_sync_reset),	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
    .auto_buffer_in_a_ready        (_mig_auto_buffer_in_a_ready),
    .auto_buffer_in_a_valid        (ddrBlockDuringReset_nodeOut_a_r & _chiptop0_tl_slave_0_a_valid),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40, generators/rocket-chip/src/main/scala/util/BlockDuringReset.scala:13:24, generators/rocket-chip/src/main/scala/util/Blockable.scala:34:18, :37:30, :38:20]
    .auto_buffer_in_a_bits_opcode  (_chiptop0_tl_slave_0_a_bits_opcode),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .auto_buffer_in_a_bits_param   (_chiptop0_tl_slave_0_a_bits_param),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .auto_buffer_in_a_bits_size    (_chiptop0_tl_slave_0_a_bits_size),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .auto_buffer_in_a_bits_source  (_chiptop0_tl_slave_0_a_bits_source),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .auto_buffer_in_a_bits_address (_chiptop0_tl_slave_0_a_bits_address),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .auto_buffer_in_a_bits_mask    (_chiptop0_tl_slave_0_a_bits_mask),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .auto_buffer_in_a_bits_data    (_chiptop0_tl_slave_0_a_bits_data),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .auto_buffer_in_a_bits_corrupt (_chiptop0_tl_slave_0_a_bits_corrupt),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .auto_buffer_in_d_ready        (ddrBlockDuringReset_nodeIn_d_r & _chiptop0_tl_slave_0_d_ready),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40, generators/rocket-chip/src/main/scala/util/BlockDuringReset.scala:13:24, generators/rocket-chip/src/main/scala/util/Blockable.scala:35:18, :37:30, :39:20]
    .auto_buffer_in_d_valid        (_mig_auto_buffer_in_d_valid),
    .auto_buffer_in_d_bits_opcode  (_mig_auto_buffer_in_d_bits_opcode),
    .auto_buffer_in_d_bits_param   (_mig_auto_buffer_in_d_bits_param),
    .auto_buffer_in_d_bits_size    (_mig_auto_buffer_in_d_bits_size),
    .auto_buffer_in_d_bits_source  (_mig_auto_buffer_in_d_bits_source),
    .auto_buffer_in_d_bits_sink    (_mig_auto_buffer_in_d_bits_sink),
    .auto_buffer_in_d_bits_denied  (_mig_auto_buffer_in_d_bits_denied),
    .auto_buffer_in_d_bits_data    (_mig_auto_buffer_in_d_bits_data),
    .auto_buffer_in_d_bits_corrupt (_mig_auto_buffer_in_d_bits_corrupt),
    .io_port_ddr3_addr             (ddr_ddr3_addr),
    .io_port_ddr3_ba               (ddr_ddr3_ba),
    .io_port_ddr3_ras_n            (ddr_ddr3_ras_n),
    .io_port_ddr3_cas_n            (ddr_ddr3_cas_n),
    .io_port_ddr3_we_n             (ddr_ddr3_we_n),
    .io_port_ddr3_reset_n          (ddr_ddr3_reset_n),
    .io_port_ddr3_ck_p             (ddr_ddr3_ck_p),
    .io_port_ddr3_ck_n             (ddr_ddr3_ck_n),
    .io_port_ddr3_cke              (ddr_ddr3_cke),
    .io_port_ddr3_dm               (ddr_ddr3_dm),
    .io_port_ddr3_odt              (ddr_ddr3_odt),
    .io_port_ddr3_dq               (ddr_ddr3_dq),
    .io_port_ddr3_dqs_n            (ddr_ddr3_dqs_n),
    .io_port_ddr3_dqs_p            (ddr_ddr3_dqs_p),
    .io_port_sys_clk_i             (_dutWrangler_auto_out_1_clock),	// @[fpga/src/main/scala/nexysvideo/Harness.scala:29:31]
    .io_port_clk_ref_i             (_dutWrangler_auto_out_2_clock),	// @[fpga/src/main/scala/nexysvideo/Harness.scala:29:31]
    .io_port_ui_clk                (_mig_io_port_ui_clk),
    .io_port_ui_clk_sync_rst       (_mig_io_port_ui_clk_sync_rst),
    .io_port_mmcm_locked           (_mig_io_port_mmcm_locked),
    .io_port_aresetn               (~_dutWrangler_auto_out_3_reset),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/NexysVideoShell.scala:306:21, fpga/src/main/scala/nexysvideo/Harness.scala:29:31]
    .io_port_init_calib_complete   (_mig_io_port_init_calib_complete),
    .io_port_sys_rst               (_GEN)	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/NexysVideoShell.scala:379:36]
  );
  harnessSysPLLNode harnessSysPLLNode (	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/XilinxShell.scala:76:55]
    .clk_in1  (_sys_clock_ibufg_O),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ClockOverlay.scala:32:22]
    .clk_out1 (_harnessSysPLLNode_clk_out1),
    .clk_out2 (_harnessSysPLLNode_clk_out2),
    .clk_out3 (_harnessSysPLLNode_clk_out3),
    .reset    (_GEN),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/NexysVideoShell.scala:379:36]
    .locked   (_harnessSysPLLNode_locked)
  );
  IBUFG sys_clock_ibufg (	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ClockOverlay.scala:32:22]
    .O (_sys_clock_ibufg_O),
    .I (sys_clock)
  );
  UIntToAnalog_1 a2b (	// @[fpga/fpga-shells/src/main/scala/shell/Util.scala:57:21]
    .a    (uart_txd),
    .b    (_chiptop0_uart_tsi_uart_txd),	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .b_en (1'h1)
  );
  AnalogToUInt_1 io_uart_bbIn_rxd_a2b (	// @[fpga/fpga-shells/src/main/scala/shell/Util.scala:29:21]
    .a (uart_rxd),
    .b (_io_uart_bbIn_rxd_a2b_b)
  );
  IBUF reset_ibuf (	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/NexysVideoShell.scala:369:28]
    .O (_reset_ibuf_O),
    .I (reset)
  );
  PowerOnResetFPGAOnly powerOnReset_fpga_power_on (	// @[fpga/fpga-shells/src/main/scala/ip/xilinx/Xilinx.scala:103:21]
    .clock          (_sys_clock_ibufg_O),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/ClockOverlay.scala:32:22]
    .power_on_reset (_powerOnReset_fpga_power_on_power_on_reset)
  );
  ChipTop chiptop0 (	// @[generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
    .port_clock                (serial_tl_clock),
    .port_bits_in_ready        (serial_tl_bits_in_ready),
    .port_bits_in_valid        (serial_tl_bits_in_valid),
    .port_bits_in_bits         (serial_tl_bits_in_bits),
    .port_bits_out_ready       (serial_tl_bits_out_ready),
    .port_bits_out_valid       (serial_tl_bits_out_valid),
    .port_bits_out_bits        (serial_tl_bits_out_bits),
    .tl_slave_0_a_ready        (ddrBlockDuringReset_nodeOut_a_r & _mig_auto_buffer_in_a_ready),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/NexysVideoShell.scala:283:23, generators/rocket-chip/src/main/scala/util/BlockDuringReset.scala:13:24, generators/rocket-chip/src/main/scala/util/Blockable.scala:35:18, :37:30, :39:20]
    .tl_slave_0_a_valid        (_chiptop0_tl_slave_0_a_valid),
    .tl_slave_0_a_bits_opcode  (_chiptop0_tl_slave_0_a_bits_opcode),
    .tl_slave_0_a_bits_param   (_chiptop0_tl_slave_0_a_bits_param),
    .tl_slave_0_a_bits_size    (_chiptop0_tl_slave_0_a_bits_size),
    .tl_slave_0_a_bits_source  (_chiptop0_tl_slave_0_a_bits_source),
    .tl_slave_0_a_bits_address (_chiptop0_tl_slave_0_a_bits_address),
    .tl_slave_0_a_bits_mask    (_chiptop0_tl_slave_0_a_bits_mask),
    .tl_slave_0_a_bits_data    (_chiptop0_tl_slave_0_a_bits_data),
    .tl_slave_0_a_bits_corrupt (_chiptop0_tl_slave_0_a_bits_corrupt),
    .tl_slave_0_d_ready        (_chiptop0_tl_slave_0_d_ready),
    .tl_slave_0_d_valid        (ddrBlockDuringReset_nodeIn_d_r & _mig_auto_buffer_in_d_valid),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/NexysVideoShell.scala:283:23, generators/rocket-chip/src/main/scala/util/BlockDuringReset.scala:13:24, generators/rocket-chip/src/main/scala/util/Blockable.scala:34:18, :37:30, :38:20]
    .tl_slave_0_d_bits_opcode  (_mig_auto_buffer_in_d_bits_opcode),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/NexysVideoShell.scala:283:23]
    .tl_slave_0_d_bits_param   (_mig_auto_buffer_in_d_bits_param),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/NexysVideoShell.scala:283:23]
    .tl_slave_0_d_bits_size    (_mig_auto_buffer_in_d_bits_size),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/NexysVideoShell.scala:283:23]
    .tl_slave_0_d_bits_source  (_mig_auto_buffer_in_d_bits_source),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/NexysVideoShell.scala:283:23]
    .tl_slave_0_d_bits_sink    (_mig_auto_buffer_in_d_bits_sink),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/NexysVideoShell.scala:283:23]
    .tl_slave_0_d_bits_denied  (_mig_auto_buffer_in_d_bits_denied),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/NexysVideoShell.scala:283:23]
    .tl_slave_0_d_bits_data    (_mig_auto_buffer_in_d_bits_data),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/NexysVideoShell.scala:283:23]
    .tl_slave_0_d_bits_corrupt (_mig_auto_buffer_in_d_bits_corrupt),	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/NexysVideoShell.scala:283:23]
    .reset_io                  (_dutWrangler_auto_out_0_reset),	// @[fpga/src/main/scala/nexysvideo/Harness.scala:29:31]
    .clock_uncore              (_dutWrangler_auto_out_0_clock),	// @[fpga/src/main/scala/nexysvideo/Harness.scala:29:31]
    .clock_serial_tl_clock_0   (_dutWrangler_auto_out_0_clock),	// @[fpga/src/main/scala/nexysvideo/Harness.scala:29:31]
    .uart_tsi_uart_txd         (_chiptop0_uart_tsi_uart_txd),
    .uart_tsi_uart_rxd         (_io_uart_bbIn_rxd_a2b_b),	// @[fpga/fpga-shells/src/main/scala/shell/Util.scala:29:21]
    .uart_tsi_dropped          (led_3),
    .uart_tsi_tsi2tl_state     (_chiptop0_uart_tsi_tsi2tl_state)
  );
  ResetCatchAndSync_d3 harnessBinderReset_catcher (	// @[generators/rocket-chip/src/main/scala/util/ResetCatchAndSync.scala:39:28]
    .clock         (_dutWrangler_auto_out_0_clock),	// @[fpga/src/main/scala/nexysvideo/Harness.scala:29:31]
    .reset         (_dutWrangler_auto_out_0_reset),	// @[fpga/src/main/scala/nexysvideo/Harness.scala:29:31]
    .io_sync_reset (_harnessBinderReset_catcher_io_sync_reset)
  );
  assign led_0 = ~REG_1;	// @[fpga/src/main/scala/nexysvideo/Harness.scala:65:23, :66:60]
  assign led_1 = REG_1;	// @[fpga/src/main/scala/nexysvideo/Harness.scala:65:23]
  assign led_2 = _reset_ibuf_O;	// @[fpga/fpga-shells/src/main/scala/shell/xilinx/NexysVideoShell.scala:369:28]
  assign led_4 = _chiptop0_uart_tsi_tsi2tl_state[0];	// @[fpga/src/main/scala/nexysvideo/HarnessBinders.scala:35:55, generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  assign led_5 = _chiptop0_uart_tsi_tsi2tl_state[1];	// @[fpga/src/main/scala/nexysvideo/HarnessBinders.scala:36:55, generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  assign led_6 = _chiptop0_uart_tsi_tsi2tl_state[2];	// @[fpga/src/main/scala/nexysvideo/HarnessBinders.scala:37:55, generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
  assign led_7 = _chiptop0_uart_tsi_tsi2tl_state[3];	// @[fpga/src/main/scala/nexysvideo/HarnessBinders.scala:38:55, generators/chipyard/src/main/scala/harness/HasHarnessInstantiators.scala:87:40]
endmodule

