// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module XilinxNexysVideoMIGIsland(
  input  [3:0]  auto_axi4in_xing_in_aw_mem_0_id,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0] auto_axi4in_xing_in_aw_mem_0_addr,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [7:0]  auto_axi4in_xing_in_aw_mem_0_len,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_axi4in_xing_in_aw_mem_0_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [1:0]  auto_axi4in_xing_in_aw_mem_0_burst,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_axi4in_xing_in_aw_mem_0_lock,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_axi4in_xing_in_aw_mem_0_cache,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_axi4in_xing_in_aw_mem_0_prot,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_axi4in_xing_in_aw_mem_0_qos,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_axi4in_xing_in_aw_mem_1_id,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0] auto_axi4in_xing_in_aw_mem_1_addr,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [7:0]  auto_axi4in_xing_in_aw_mem_1_len,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_axi4in_xing_in_aw_mem_1_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [1:0]  auto_axi4in_xing_in_aw_mem_1_burst,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_axi4in_xing_in_aw_mem_1_lock,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_axi4in_xing_in_aw_mem_1_cache,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_axi4in_xing_in_aw_mem_1_prot,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_axi4in_xing_in_aw_mem_1_qos,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_axi4in_xing_in_aw_mem_2_id,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0] auto_axi4in_xing_in_aw_mem_2_addr,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [7:0]  auto_axi4in_xing_in_aw_mem_2_len,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_axi4in_xing_in_aw_mem_2_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [1:0]  auto_axi4in_xing_in_aw_mem_2_burst,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_axi4in_xing_in_aw_mem_2_lock,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_axi4in_xing_in_aw_mem_2_cache,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_axi4in_xing_in_aw_mem_2_prot,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_axi4in_xing_in_aw_mem_2_qos,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_axi4in_xing_in_aw_mem_3_id,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0] auto_axi4in_xing_in_aw_mem_3_addr,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [7:0]  auto_axi4in_xing_in_aw_mem_3_len,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_axi4in_xing_in_aw_mem_3_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [1:0]  auto_axi4in_xing_in_aw_mem_3_burst,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_axi4in_xing_in_aw_mem_3_lock,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_axi4in_xing_in_aw_mem_3_cache,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_axi4in_xing_in_aw_mem_3_prot,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_axi4in_xing_in_aw_mem_3_qos,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_axi4in_xing_in_aw_mem_4_id,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0] auto_axi4in_xing_in_aw_mem_4_addr,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [7:0]  auto_axi4in_xing_in_aw_mem_4_len,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_axi4in_xing_in_aw_mem_4_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [1:0]  auto_axi4in_xing_in_aw_mem_4_burst,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_axi4in_xing_in_aw_mem_4_lock,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_axi4in_xing_in_aw_mem_4_cache,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_axi4in_xing_in_aw_mem_4_prot,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_axi4in_xing_in_aw_mem_4_qos,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_axi4in_xing_in_aw_mem_5_id,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0] auto_axi4in_xing_in_aw_mem_5_addr,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [7:0]  auto_axi4in_xing_in_aw_mem_5_len,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_axi4in_xing_in_aw_mem_5_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [1:0]  auto_axi4in_xing_in_aw_mem_5_burst,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_axi4in_xing_in_aw_mem_5_lock,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_axi4in_xing_in_aw_mem_5_cache,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_axi4in_xing_in_aw_mem_5_prot,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_axi4in_xing_in_aw_mem_5_qos,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_axi4in_xing_in_aw_mem_6_id,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0] auto_axi4in_xing_in_aw_mem_6_addr,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [7:0]  auto_axi4in_xing_in_aw_mem_6_len,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_axi4in_xing_in_aw_mem_6_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [1:0]  auto_axi4in_xing_in_aw_mem_6_burst,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_axi4in_xing_in_aw_mem_6_lock,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_axi4in_xing_in_aw_mem_6_cache,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_axi4in_xing_in_aw_mem_6_prot,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_axi4in_xing_in_aw_mem_6_qos,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_axi4in_xing_in_aw_mem_7_id,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0] auto_axi4in_xing_in_aw_mem_7_addr,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [7:0]  auto_axi4in_xing_in_aw_mem_7_len,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_axi4in_xing_in_aw_mem_7_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [1:0]  auto_axi4in_xing_in_aw_mem_7_burst,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_axi4in_xing_in_aw_mem_7_lock,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_axi4in_xing_in_aw_mem_7_cache,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_axi4in_xing_in_aw_mem_7_prot,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_axi4in_xing_in_aw_mem_7_qos,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]  auto_axi4in_xing_in_aw_ridx,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_axi4in_xing_in_aw_widx,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_axi4in_xing_in_aw_safe_ridx_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_axi4in_xing_in_aw_safe_widx_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_axi4in_xing_in_aw_safe_source_reset_n,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_axi4in_xing_in_aw_safe_sink_reset_n,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [63:0] auto_axi4in_xing_in_w_mem_0_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [7:0]  auto_axi4in_xing_in_w_mem_0_strb,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_axi4in_xing_in_w_mem_0_last,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [63:0] auto_axi4in_xing_in_w_mem_1_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [7:0]  auto_axi4in_xing_in_w_mem_1_strb,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_axi4in_xing_in_w_mem_1_last,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [63:0] auto_axi4in_xing_in_w_mem_2_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [7:0]  auto_axi4in_xing_in_w_mem_2_strb,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_axi4in_xing_in_w_mem_2_last,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [63:0] auto_axi4in_xing_in_w_mem_3_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [7:0]  auto_axi4in_xing_in_w_mem_3_strb,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_axi4in_xing_in_w_mem_3_last,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [63:0] auto_axi4in_xing_in_w_mem_4_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [7:0]  auto_axi4in_xing_in_w_mem_4_strb,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_axi4in_xing_in_w_mem_4_last,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [63:0] auto_axi4in_xing_in_w_mem_5_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [7:0]  auto_axi4in_xing_in_w_mem_5_strb,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_axi4in_xing_in_w_mem_5_last,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [63:0] auto_axi4in_xing_in_w_mem_6_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [7:0]  auto_axi4in_xing_in_w_mem_6_strb,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_axi4in_xing_in_w_mem_6_last,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [63:0] auto_axi4in_xing_in_w_mem_7_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [7:0]  auto_axi4in_xing_in_w_mem_7_strb,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_axi4in_xing_in_w_mem_7_last,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]  auto_axi4in_xing_in_w_ridx,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_axi4in_xing_in_w_widx,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_axi4in_xing_in_w_safe_ridx_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_axi4in_xing_in_w_safe_widx_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_axi4in_xing_in_w_safe_source_reset_n,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_axi4in_xing_in_w_safe_sink_reset_n,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]  auto_axi4in_xing_in_b_mem_0_id,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [1:0]  auto_axi4in_xing_in_b_mem_0_resp,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]  auto_axi4in_xing_in_b_mem_1_id,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [1:0]  auto_axi4in_xing_in_b_mem_1_resp,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]  auto_axi4in_xing_in_b_mem_2_id,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [1:0]  auto_axi4in_xing_in_b_mem_2_resp,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]  auto_axi4in_xing_in_b_mem_3_id,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [1:0]  auto_axi4in_xing_in_b_mem_3_resp,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]  auto_axi4in_xing_in_b_mem_4_id,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [1:0]  auto_axi4in_xing_in_b_mem_4_resp,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]  auto_axi4in_xing_in_b_mem_5_id,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [1:0]  auto_axi4in_xing_in_b_mem_5_resp,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]  auto_axi4in_xing_in_b_mem_6_id,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [1:0]  auto_axi4in_xing_in_b_mem_6_resp,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]  auto_axi4in_xing_in_b_mem_7_id,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [1:0]  auto_axi4in_xing_in_b_mem_7_resp,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_axi4in_xing_in_b_ridx,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]  auto_axi4in_xing_in_b_widx,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_axi4in_xing_in_b_safe_ridx_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_axi4in_xing_in_b_safe_widx_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_axi4in_xing_in_b_safe_source_reset_n,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_axi4in_xing_in_b_safe_sink_reset_n,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_axi4in_xing_in_ar_mem_0_id,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0] auto_axi4in_xing_in_ar_mem_0_addr,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [7:0]  auto_axi4in_xing_in_ar_mem_0_len,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_axi4in_xing_in_ar_mem_0_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [1:0]  auto_axi4in_xing_in_ar_mem_0_burst,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_axi4in_xing_in_ar_mem_0_lock,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_axi4in_xing_in_ar_mem_0_cache,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_axi4in_xing_in_ar_mem_0_prot,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_axi4in_xing_in_ar_mem_0_qos,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_axi4in_xing_in_ar_mem_1_id,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0] auto_axi4in_xing_in_ar_mem_1_addr,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [7:0]  auto_axi4in_xing_in_ar_mem_1_len,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_axi4in_xing_in_ar_mem_1_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [1:0]  auto_axi4in_xing_in_ar_mem_1_burst,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_axi4in_xing_in_ar_mem_1_lock,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_axi4in_xing_in_ar_mem_1_cache,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_axi4in_xing_in_ar_mem_1_prot,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_axi4in_xing_in_ar_mem_1_qos,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_axi4in_xing_in_ar_mem_2_id,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0] auto_axi4in_xing_in_ar_mem_2_addr,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [7:0]  auto_axi4in_xing_in_ar_mem_2_len,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_axi4in_xing_in_ar_mem_2_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [1:0]  auto_axi4in_xing_in_ar_mem_2_burst,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_axi4in_xing_in_ar_mem_2_lock,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_axi4in_xing_in_ar_mem_2_cache,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_axi4in_xing_in_ar_mem_2_prot,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_axi4in_xing_in_ar_mem_2_qos,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_axi4in_xing_in_ar_mem_3_id,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0] auto_axi4in_xing_in_ar_mem_3_addr,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [7:0]  auto_axi4in_xing_in_ar_mem_3_len,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_axi4in_xing_in_ar_mem_3_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [1:0]  auto_axi4in_xing_in_ar_mem_3_burst,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_axi4in_xing_in_ar_mem_3_lock,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_axi4in_xing_in_ar_mem_3_cache,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_axi4in_xing_in_ar_mem_3_prot,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_axi4in_xing_in_ar_mem_3_qos,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_axi4in_xing_in_ar_mem_4_id,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0] auto_axi4in_xing_in_ar_mem_4_addr,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [7:0]  auto_axi4in_xing_in_ar_mem_4_len,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_axi4in_xing_in_ar_mem_4_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [1:0]  auto_axi4in_xing_in_ar_mem_4_burst,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_axi4in_xing_in_ar_mem_4_lock,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_axi4in_xing_in_ar_mem_4_cache,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_axi4in_xing_in_ar_mem_4_prot,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_axi4in_xing_in_ar_mem_4_qos,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_axi4in_xing_in_ar_mem_5_id,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0] auto_axi4in_xing_in_ar_mem_5_addr,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [7:0]  auto_axi4in_xing_in_ar_mem_5_len,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_axi4in_xing_in_ar_mem_5_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [1:0]  auto_axi4in_xing_in_ar_mem_5_burst,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_axi4in_xing_in_ar_mem_5_lock,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_axi4in_xing_in_ar_mem_5_cache,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_axi4in_xing_in_ar_mem_5_prot,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_axi4in_xing_in_ar_mem_5_qos,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_axi4in_xing_in_ar_mem_6_id,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0] auto_axi4in_xing_in_ar_mem_6_addr,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [7:0]  auto_axi4in_xing_in_ar_mem_6_len,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_axi4in_xing_in_ar_mem_6_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [1:0]  auto_axi4in_xing_in_ar_mem_6_burst,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_axi4in_xing_in_ar_mem_6_lock,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_axi4in_xing_in_ar_mem_6_cache,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_axi4in_xing_in_ar_mem_6_prot,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_axi4in_xing_in_ar_mem_6_qos,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_axi4in_xing_in_ar_mem_7_id,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [31:0] auto_axi4in_xing_in_ar_mem_7_addr,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [7:0]  auto_axi4in_xing_in_ar_mem_7_len,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_axi4in_xing_in_ar_mem_7_size,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [1:0]  auto_axi4in_xing_in_ar_mem_7_burst,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_axi4in_xing_in_ar_mem_7_lock,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_axi4in_xing_in_ar_mem_7_cache,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [2:0]  auto_axi4in_xing_in_ar_mem_7_prot,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_axi4in_xing_in_ar_mem_7_qos,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]  auto_axi4in_xing_in_ar_ridx,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_axi4in_xing_in_ar_widx,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_axi4in_xing_in_ar_safe_ridx_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_axi4in_xing_in_ar_safe_widx_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_axi4in_xing_in_ar_safe_source_reset_n,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_axi4in_xing_in_ar_safe_sink_reset_n,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]  auto_axi4in_xing_in_r_mem_0_id,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [63:0] auto_axi4in_xing_in_r_mem_0_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [1:0]  auto_axi4in_xing_in_r_mem_0_resp,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_axi4in_xing_in_r_mem_0_last,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]  auto_axi4in_xing_in_r_mem_1_id,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [63:0] auto_axi4in_xing_in_r_mem_1_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [1:0]  auto_axi4in_xing_in_r_mem_1_resp,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_axi4in_xing_in_r_mem_1_last,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]  auto_axi4in_xing_in_r_mem_2_id,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [63:0] auto_axi4in_xing_in_r_mem_2_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [1:0]  auto_axi4in_xing_in_r_mem_2_resp,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_axi4in_xing_in_r_mem_2_last,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]  auto_axi4in_xing_in_r_mem_3_id,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [63:0] auto_axi4in_xing_in_r_mem_3_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [1:0]  auto_axi4in_xing_in_r_mem_3_resp,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_axi4in_xing_in_r_mem_3_last,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]  auto_axi4in_xing_in_r_mem_4_id,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [63:0] auto_axi4in_xing_in_r_mem_4_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [1:0]  auto_axi4in_xing_in_r_mem_4_resp,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_axi4in_xing_in_r_mem_4_last,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]  auto_axi4in_xing_in_r_mem_5_id,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [63:0] auto_axi4in_xing_in_r_mem_5_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [1:0]  auto_axi4in_xing_in_r_mem_5_resp,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_axi4in_xing_in_r_mem_5_last,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]  auto_axi4in_xing_in_r_mem_6_id,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [63:0] auto_axi4in_xing_in_r_mem_6_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [1:0]  auto_axi4in_xing_in_r_mem_6_resp,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_axi4in_xing_in_r_mem_6_last,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]  auto_axi4in_xing_in_r_mem_7_id,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [63:0] auto_axi4in_xing_in_r_mem_7_data,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [1:0]  auto_axi4in_xing_in_r_mem_7_resp,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_axi4in_xing_in_r_mem_7_last,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input  [3:0]  auto_axi4in_xing_in_r_ridx,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [3:0]  auto_axi4in_xing_in_r_widx,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_axi4in_xing_in_r_safe_ridx_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output        auto_axi4in_xing_in_r_safe_widx_valid,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
                auto_axi4in_xing_in_r_safe_source_reset_n,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  input         auto_axi4in_xing_in_r_safe_sink_reset_n,	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:367:18]
  output [14:0] io_port_ddr3_addr,	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:44:16]
  output [2:0]  io_port_ddr3_ba,	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:44:16]
  output        io_port_ddr3_ras_n,	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:44:16]
                io_port_ddr3_cas_n,	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:44:16]
                io_port_ddr3_we_n,	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:44:16]
                io_port_ddr3_reset_n,	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:44:16]
                io_port_ddr3_ck_p,	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:44:16]
                io_port_ddr3_ck_n,	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:44:16]
                io_port_ddr3_cke,	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:44:16]
  output [1:0]  io_port_ddr3_dm,	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:44:16]
  output        io_port_ddr3_odt,	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:44:16]
  inout  [15:0] io_port_ddr3_dq,	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:44:16]
  inout  [1:0]  io_port_ddr3_dqs_n,	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:44:16]
                io_port_ddr3_dqs_p,	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:44:16]
  input         io_port_sys_clk_i,	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:44:16]
                io_port_clk_ref_i,	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:44:16]
  output        io_port_ui_clk,	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:44:16]
                io_port_ui_clk_sync_rst,	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:44:16]
                io_port_mmcm_locked,	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:44:16]
  input         io_port_aresetn,	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:44:16]
  output        io_port_init_calib_complete,	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:44:16]
  input         io_port_sys_rst	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:44:16]
);

  wire        _blackbox_ui_clk;	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:52:26]
  wire        _blackbox_ui_clk_sync_rst;	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:52:26]
  wire        _blackbox_s_axi_awready;	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:52:26]
  wire        _blackbox_s_axi_wready;	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:52:26]
  wire [3:0]  _blackbox_s_axi_bid;	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:52:26]
  wire [1:0]  _blackbox_s_axi_bresp;	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:52:26]
  wire        _blackbox_s_axi_bvalid;	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:52:26]
  wire        _blackbox_s_axi_arready;	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:52:26]
  wire [3:0]  _blackbox_s_axi_rid;	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:52:26]
  wire [63:0] _blackbox_s_axi_rdata;	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:52:26]
  wire [1:0]  _blackbox_s_axi_rresp;	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:52:26]
  wire        _blackbox_s_axi_rlast;	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:52:26]
  wire        _blackbox_s_axi_rvalid;	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:52:26]
  wire        _axi4asink_auto_out_aw_valid;	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
  wire [3:0]  _axi4asink_auto_out_aw_bits_id;	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
  wire [31:0] _axi4asink_auto_out_aw_bits_addr;	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
  wire [7:0]  _axi4asink_auto_out_aw_bits_len;	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
  wire [2:0]  _axi4asink_auto_out_aw_bits_size;	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
  wire [1:0]  _axi4asink_auto_out_aw_bits_burst;	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
  wire        _axi4asink_auto_out_aw_bits_lock;	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
  wire [2:0]  _axi4asink_auto_out_aw_bits_prot;	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
  wire [3:0]  _axi4asink_auto_out_aw_bits_qos;	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
  wire        _axi4asink_auto_out_w_valid;	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
  wire [63:0] _axi4asink_auto_out_w_bits_data;	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
  wire [7:0]  _axi4asink_auto_out_w_bits_strb;	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
  wire        _axi4asink_auto_out_w_bits_last;	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
  wire        _axi4asink_auto_out_b_ready;	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
  wire        _axi4asink_auto_out_ar_valid;	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
  wire [3:0]  _axi4asink_auto_out_ar_bits_id;	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
  wire [31:0] _axi4asink_auto_out_ar_bits_addr;	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
  wire [7:0]  _axi4asink_auto_out_ar_bits_len;	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
  wire [2:0]  _axi4asink_auto_out_ar_bits_size;	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
  wire [1:0]  _axi4asink_auto_out_ar_bits_burst;	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
  wire        _axi4asink_auto_out_ar_bits_lock;	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
  wire [2:0]  _axi4asink_auto_out_ar_bits_prot;	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
  wire [3:0]  _axi4asink_auto_out_ar_bits_qos;	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
  wire        _axi4asink_auto_out_r_ready;	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
  AXI4AsyncCrossingSink axi4asink (	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
    .clock                          (_blackbox_ui_clk),	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:52:26]
    .reset                          (_blackbox_ui_clk_sync_rst),	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:52:26]
    .auto_in_aw_mem_0_id            (auto_axi4in_xing_in_aw_mem_0_id),
    .auto_in_aw_mem_0_addr          (auto_axi4in_xing_in_aw_mem_0_addr),
    .auto_in_aw_mem_0_len           (auto_axi4in_xing_in_aw_mem_0_len),
    .auto_in_aw_mem_0_size          (auto_axi4in_xing_in_aw_mem_0_size),
    .auto_in_aw_mem_0_burst         (auto_axi4in_xing_in_aw_mem_0_burst),
    .auto_in_aw_mem_0_lock          (auto_axi4in_xing_in_aw_mem_0_lock),
    .auto_in_aw_mem_0_cache         (auto_axi4in_xing_in_aw_mem_0_cache),
    .auto_in_aw_mem_0_prot          (auto_axi4in_xing_in_aw_mem_0_prot),
    .auto_in_aw_mem_0_qos           (auto_axi4in_xing_in_aw_mem_0_qos),
    .auto_in_aw_mem_1_id            (auto_axi4in_xing_in_aw_mem_1_id),
    .auto_in_aw_mem_1_addr          (auto_axi4in_xing_in_aw_mem_1_addr),
    .auto_in_aw_mem_1_len           (auto_axi4in_xing_in_aw_mem_1_len),
    .auto_in_aw_mem_1_size          (auto_axi4in_xing_in_aw_mem_1_size),
    .auto_in_aw_mem_1_burst         (auto_axi4in_xing_in_aw_mem_1_burst),
    .auto_in_aw_mem_1_lock          (auto_axi4in_xing_in_aw_mem_1_lock),
    .auto_in_aw_mem_1_cache         (auto_axi4in_xing_in_aw_mem_1_cache),
    .auto_in_aw_mem_1_prot          (auto_axi4in_xing_in_aw_mem_1_prot),
    .auto_in_aw_mem_1_qos           (auto_axi4in_xing_in_aw_mem_1_qos),
    .auto_in_aw_mem_2_id            (auto_axi4in_xing_in_aw_mem_2_id),
    .auto_in_aw_mem_2_addr          (auto_axi4in_xing_in_aw_mem_2_addr),
    .auto_in_aw_mem_2_len           (auto_axi4in_xing_in_aw_mem_2_len),
    .auto_in_aw_mem_2_size          (auto_axi4in_xing_in_aw_mem_2_size),
    .auto_in_aw_mem_2_burst         (auto_axi4in_xing_in_aw_mem_2_burst),
    .auto_in_aw_mem_2_lock          (auto_axi4in_xing_in_aw_mem_2_lock),
    .auto_in_aw_mem_2_cache         (auto_axi4in_xing_in_aw_mem_2_cache),
    .auto_in_aw_mem_2_prot          (auto_axi4in_xing_in_aw_mem_2_prot),
    .auto_in_aw_mem_2_qos           (auto_axi4in_xing_in_aw_mem_2_qos),
    .auto_in_aw_mem_3_id            (auto_axi4in_xing_in_aw_mem_3_id),
    .auto_in_aw_mem_3_addr          (auto_axi4in_xing_in_aw_mem_3_addr),
    .auto_in_aw_mem_3_len           (auto_axi4in_xing_in_aw_mem_3_len),
    .auto_in_aw_mem_3_size          (auto_axi4in_xing_in_aw_mem_3_size),
    .auto_in_aw_mem_3_burst         (auto_axi4in_xing_in_aw_mem_3_burst),
    .auto_in_aw_mem_3_lock          (auto_axi4in_xing_in_aw_mem_3_lock),
    .auto_in_aw_mem_3_cache         (auto_axi4in_xing_in_aw_mem_3_cache),
    .auto_in_aw_mem_3_prot          (auto_axi4in_xing_in_aw_mem_3_prot),
    .auto_in_aw_mem_3_qos           (auto_axi4in_xing_in_aw_mem_3_qos),
    .auto_in_aw_mem_4_id            (auto_axi4in_xing_in_aw_mem_4_id),
    .auto_in_aw_mem_4_addr          (auto_axi4in_xing_in_aw_mem_4_addr),
    .auto_in_aw_mem_4_len           (auto_axi4in_xing_in_aw_mem_4_len),
    .auto_in_aw_mem_4_size          (auto_axi4in_xing_in_aw_mem_4_size),
    .auto_in_aw_mem_4_burst         (auto_axi4in_xing_in_aw_mem_4_burst),
    .auto_in_aw_mem_4_lock          (auto_axi4in_xing_in_aw_mem_4_lock),
    .auto_in_aw_mem_4_cache         (auto_axi4in_xing_in_aw_mem_4_cache),
    .auto_in_aw_mem_4_prot          (auto_axi4in_xing_in_aw_mem_4_prot),
    .auto_in_aw_mem_4_qos           (auto_axi4in_xing_in_aw_mem_4_qos),
    .auto_in_aw_mem_5_id            (auto_axi4in_xing_in_aw_mem_5_id),
    .auto_in_aw_mem_5_addr          (auto_axi4in_xing_in_aw_mem_5_addr),
    .auto_in_aw_mem_5_len           (auto_axi4in_xing_in_aw_mem_5_len),
    .auto_in_aw_mem_5_size          (auto_axi4in_xing_in_aw_mem_5_size),
    .auto_in_aw_mem_5_burst         (auto_axi4in_xing_in_aw_mem_5_burst),
    .auto_in_aw_mem_5_lock          (auto_axi4in_xing_in_aw_mem_5_lock),
    .auto_in_aw_mem_5_cache         (auto_axi4in_xing_in_aw_mem_5_cache),
    .auto_in_aw_mem_5_prot          (auto_axi4in_xing_in_aw_mem_5_prot),
    .auto_in_aw_mem_5_qos           (auto_axi4in_xing_in_aw_mem_5_qos),
    .auto_in_aw_mem_6_id            (auto_axi4in_xing_in_aw_mem_6_id),
    .auto_in_aw_mem_6_addr          (auto_axi4in_xing_in_aw_mem_6_addr),
    .auto_in_aw_mem_6_len           (auto_axi4in_xing_in_aw_mem_6_len),
    .auto_in_aw_mem_6_size          (auto_axi4in_xing_in_aw_mem_6_size),
    .auto_in_aw_mem_6_burst         (auto_axi4in_xing_in_aw_mem_6_burst),
    .auto_in_aw_mem_6_lock          (auto_axi4in_xing_in_aw_mem_6_lock),
    .auto_in_aw_mem_6_cache         (auto_axi4in_xing_in_aw_mem_6_cache),
    .auto_in_aw_mem_6_prot          (auto_axi4in_xing_in_aw_mem_6_prot),
    .auto_in_aw_mem_6_qos           (auto_axi4in_xing_in_aw_mem_6_qos),
    .auto_in_aw_mem_7_id            (auto_axi4in_xing_in_aw_mem_7_id),
    .auto_in_aw_mem_7_addr          (auto_axi4in_xing_in_aw_mem_7_addr),
    .auto_in_aw_mem_7_len           (auto_axi4in_xing_in_aw_mem_7_len),
    .auto_in_aw_mem_7_size          (auto_axi4in_xing_in_aw_mem_7_size),
    .auto_in_aw_mem_7_burst         (auto_axi4in_xing_in_aw_mem_7_burst),
    .auto_in_aw_mem_7_lock          (auto_axi4in_xing_in_aw_mem_7_lock),
    .auto_in_aw_mem_7_cache         (auto_axi4in_xing_in_aw_mem_7_cache),
    .auto_in_aw_mem_7_prot          (auto_axi4in_xing_in_aw_mem_7_prot),
    .auto_in_aw_mem_7_qos           (auto_axi4in_xing_in_aw_mem_7_qos),
    .auto_in_aw_ridx                (auto_axi4in_xing_in_aw_ridx),
    .auto_in_aw_widx                (auto_axi4in_xing_in_aw_widx),
    .auto_in_aw_safe_ridx_valid     (auto_axi4in_xing_in_aw_safe_ridx_valid),
    .auto_in_aw_safe_widx_valid     (auto_axi4in_xing_in_aw_safe_widx_valid),
    .auto_in_aw_safe_source_reset_n (auto_axi4in_xing_in_aw_safe_source_reset_n),
    .auto_in_aw_safe_sink_reset_n   (auto_axi4in_xing_in_aw_safe_sink_reset_n),
    .auto_in_w_mem_0_data           (auto_axi4in_xing_in_w_mem_0_data),
    .auto_in_w_mem_0_strb           (auto_axi4in_xing_in_w_mem_0_strb),
    .auto_in_w_mem_0_last           (auto_axi4in_xing_in_w_mem_0_last),
    .auto_in_w_mem_1_data           (auto_axi4in_xing_in_w_mem_1_data),
    .auto_in_w_mem_1_strb           (auto_axi4in_xing_in_w_mem_1_strb),
    .auto_in_w_mem_1_last           (auto_axi4in_xing_in_w_mem_1_last),
    .auto_in_w_mem_2_data           (auto_axi4in_xing_in_w_mem_2_data),
    .auto_in_w_mem_2_strb           (auto_axi4in_xing_in_w_mem_2_strb),
    .auto_in_w_mem_2_last           (auto_axi4in_xing_in_w_mem_2_last),
    .auto_in_w_mem_3_data           (auto_axi4in_xing_in_w_mem_3_data),
    .auto_in_w_mem_3_strb           (auto_axi4in_xing_in_w_mem_3_strb),
    .auto_in_w_mem_3_last           (auto_axi4in_xing_in_w_mem_3_last),
    .auto_in_w_mem_4_data           (auto_axi4in_xing_in_w_mem_4_data),
    .auto_in_w_mem_4_strb           (auto_axi4in_xing_in_w_mem_4_strb),
    .auto_in_w_mem_4_last           (auto_axi4in_xing_in_w_mem_4_last),
    .auto_in_w_mem_5_data           (auto_axi4in_xing_in_w_mem_5_data),
    .auto_in_w_mem_5_strb           (auto_axi4in_xing_in_w_mem_5_strb),
    .auto_in_w_mem_5_last           (auto_axi4in_xing_in_w_mem_5_last),
    .auto_in_w_mem_6_data           (auto_axi4in_xing_in_w_mem_6_data),
    .auto_in_w_mem_6_strb           (auto_axi4in_xing_in_w_mem_6_strb),
    .auto_in_w_mem_6_last           (auto_axi4in_xing_in_w_mem_6_last),
    .auto_in_w_mem_7_data           (auto_axi4in_xing_in_w_mem_7_data),
    .auto_in_w_mem_7_strb           (auto_axi4in_xing_in_w_mem_7_strb),
    .auto_in_w_mem_7_last           (auto_axi4in_xing_in_w_mem_7_last),
    .auto_in_w_ridx                 (auto_axi4in_xing_in_w_ridx),
    .auto_in_w_widx                 (auto_axi4in_xing_in_w_widx),
    .auto_in_w_safe_ridx_valid      (auto_axi4in_xing_in_w_safe_ridx_valid),
    .auto_in_w_safe_widx_valid      (auto_axi4in_xing_in_w_safe_widx_valid),
    .auto_in_w_safe_source_reset_n  (auto_axi4in_xing_in_w_safe_source_reset_n),
    .auto_in_w_safe_sink_reset_n    (auto_axi4in_xing_in_w_safe_sink_reset_n),
    .auto_in_b_mem_0_id             (auto_axi4in_xing_in_b_mem_0_id),
    .auto_in_b_mem_0_resp           (auto_axi4in_xing_in_b_mem_0_resp),
    .auto_in_b_mem_1_id             (auto_axi4in_xing_in_b_mem_1_id),
    .auto_in_b_mem_1_resp           (auto_axi4in_xing_in_b_mem_1_resp),
    .auto_in_b_mem_2_id             (auto_axi4in_xing_in_b_mem_2_id),
    .auto_in_b_mem_2_resp           (auto_axi4in_xing_in_b_mem_2_resp),
    .auto_in_b_mem_3_id             (auto_axi4in_xing_in_b_mem_3_id),
    .auto_in_b_mem_3_resp           (auto_axi4in_xing_in_b_mem_3_resp),
    .auto_in_b_mem_4_id             (auto_axi4in_xing_in_b_mem_4_id),
    .auto_in_b_mem_4_resp           (auto_axi4in_xing_in_b_mem_4_resp),
    .auto_in_b_mem_5_id             (auto_axi4in_xing_in_b_mem_5_id),
    .auto_in_b_mem_5_resp           (auto_axi4in_xing_in_b_mem_5_resp),
    .auto_in_b_mem_6_id             (auto_axi4in_xing_in_b_mem_6_id),
    .auto_in_b_mem_6_resp           (auto_axi4in_xing_in_b_mem_6_resp),
    .auto_in_b_mem_7_id             (auto_axi4in_xing_in_b_mem_7_id),
    .auto_in_b_mem_7_resp           (auto_axi4in_xing_in_b_mem_7_resp),
    .auto_in_b_ridx                 (auto_axi4in_xing_in_b_ridx),
    .auto_in_b_widx                 (auto_axi4in_xing_in_b_widx),
    .auto_in_b_safe_ridx_valid      (auto_axi4in_xing_in_b_safe_ridx_valid),
    .auto_in_b_safe_widx_valid      (auto_axi4in_xing_in_b_safe_widx_valid),
    .auto_in_b_safe_source_reset_n  (auto_axi4in_xing_in_b_safe_source_reset_n),
    .auto_in_b_safe_sink_reset_n    (auto_axi4in_xing_in_b_safe_sink_reset_n),
    .auto_in_ar_mem_0_id            (auto_axi4in_xing_in_ar_mem_0_id),
    .auto_in_ar_mem_0_addr          (auto_axi4in_xing_in_ar_mem_0_addr),
    .auto_in_ar_mem_0_len           (auto_axi4in_xing_in_ar_mem_0_len),
    .auto_in_ar_mem_0_size          (auto_axi4in_xing_in_ar_mem_0_size),
    .auto_in_ar_mem_0_burst         (auto_axi4in_xing_in_ar_mem_0_burst),
    .auto_in_ar_mem_0_lock          (auto_axi4in_xing_in_ar_mem_0_lock),
    .auto_in_ar_mem_0_cache         (auto_axi4in_xing_in_ar_mem_0_cache),
    .auto_in_ar_mem_0_prot          (auto_axi4in_xing_in_ar_mem_0_prot),
    .auto_in_ar_mem_0_qos           (auto_axi4in_xing_in_ar_mem_0_qos),
    .auto_in_ar_mem_1_id            (auto_axi4in_xing_in_ar_mem_1_id),
    .auto_in_ar_mem_1_addr          (auto_axi4in_xing_in_ar_mem_1_addr),
    .auto_in_ar_mem_1_len           (auto_axi4in_xing_in_ar_mem_1_len),
    .auto_in_ar_mem_1_size          (auto_axi4in_xing_in_ar_mem_1_size),
    .auto_in_ar_mem_1_burst         (auto_axi4in_xing_in_ar_mem_1_burst),
    .auto_in_ar_mem_1_lock          (auto_axi4in_xing_in_ar_mem_1_lock),
    .auto_in_ar_mem_1_cache         (auto_axi4in_xing_in_ar_mem_1_cache),
    .auto_in_ar_mem_1_prot          (auto_axi4in_xing_in_ar_mem_1_prot),
    .auto_in_ar_mem_1_qos           (auto_axi4in_xing_in_ar_mem_1_qos),
    .auto_in_ar_mem_2_id            (auto_axi4in_xing_in_ar_mem_2_id),
    .auto_in_ar_mem_2_addr          (auto_axi4in_xing_in_ar_mem_2_addr),
    .auto_in_ar_mem_2_len           (auto_axi4in_xing_in_ar_mem_2_len),
    .auto_in_ar_mem_2_size          (auto_axi4in_xing_in_ar_mem_2_size),
    .auto_in_ar_mem_2_burst         (auto_axi4in_xing_in_ar_mem_2_burst),
    .auto_in_ar_mem_2_lock          (auto_axi4in_xing_in_ar_mem_2_lock),
    .auto_in_ar_mem_2_cache         (auto_axi4in_xing_in_ar_mem_2_cache),
    .auto_in_ar_mem_2_prot          (auto_axi4in_xing_in_ar_mem_2_prot),
    .auto_in_ar_mem_2_qos           (auto_axi4in_xing_in_ar_mem_2_qos),
    .auto_in_ar_mem_3_id            (auto_axi4in_xing_in_ar_mem_3_id),
    .auto_in_ar_mem_3_addr          (auto_axi4in_xing_in_ar_mem_3_addr),
    .auto_in_ar_mem_3_len           (auto_axi4in_xing_in_ar_mem_3_len),
    .auto_in_ar_mem_3_size          (auto_axi4in_xing_in_ar_mem_3_size),
    .auto_in_ar_mem_3_burst         (auto_axi4in_xing_in_ar_mem_3_burst),
    .auto_in_ar_mem_3_lock          (auto_axi4in_xing_in_ar_mem_3_lock),
    .auto_in_ar_mem_3_cache         (auto_axi4in_xing_in_ar_mem_3_cache),
    .auto_in_ar_mem_3_prot          (auto_axi4in_xing_in_ar_mem_3_prot),
    .auto_in_ar_mem_3_qos           (auto_axi4in_xing_in_ar_mem_3_qos),
    .auto_in_ar_mem_4_id            (auto_axi4in_xing_in_ar_mem_4_id),
    .auto_in_ar_mem_4_addr          (auto_axi4in_xing_in_ar_mem_4_addr),
    .auto_in_ar_mem_4_len           (auto_axi4in_xing_in_ar_mem_4_len),
    .auto_in_ar_mem_4_size          (auto_axi4in_xing_in_ar_mem_4_size),
    .auto_in_ar_mem_4_burst         (auto_axi4in_xing_in_ar_mem_4_burst),
    .auto_in_ar_mem_4_lock          (auto_axi4in_xing_in_ar_mem_4_lock),
    .auto_in_ar_mem_4_cache         (auto_axi4in_xing_in_ar_mem_4_cache),
    .auto_in_ar_mem_4_prot          (auto_axi4in_xing_in_ar_mem_4_prot),
    .auto_in_ar_mem_4_qos           (auto_axi4in_xing_in_ar_mem_4_qos),
    .auto_in_ar_mem_5_id            (auto_axi4in_xing_in_ar_mem_5_id),
    .auto_in_ar_mem_5_addr          (auto_axi4in_xing_in_ar_mem_5_addr),
    .auto_in_ar_mem_5_len           (auto_axi4in_xing_in_ar_mem_5_len),
    .auto_in_ar_mem_5_size          (auto_axi4in_xing_in_ar_mem_5_size),
    .auto_in_ar_mem_5_burst         (auto_axi4in_xing_in_ar_mem_5_burst),
    .auto_in_ar_mem_5_lock          (auto_axi4in_xing_in_ar_mem_5_lock),
    .auto_in_ar_mem_5_cache         (auto_axi4in_xing_in_ar_mem_5_cache),
    .auto_in_ar_mem_5_prot          (auto_axi4in_xing_in_ar_mem_5_prot),
    .auto_in_ar_mem_5_qos           (auto_axi4in_xing_in_ar_mem_5_qos),
    .auto_in_ar_mem_6_id            (auto_axi4in_xing_in_ar_mem_6_id),
    .auto_in_ar_mem_6_addr          (auto_axi4in_xing_in_ar_mem_6_addr),
    .auto_in_ar_mem_6_len           (auto_axi4in_xing_in_ar_mem_6_len),
    .auto_in_ar_mem_6_size          (auto_axi4in_xing_in_ar_mem_6_size),
    .auto_in_ar_mem_6_burst         (auto_axi4in_xing_in_ar_mem_6_burst),
    .auto_in_ar_mem_6_lock          (auto_axi4in_xing_in_ar_mem_6_lock),
    .auto_in_ar_mem_6_cache         (auto_axi4in_xing_in_ar_mem_6_cache),
    .auto_in_ar_mem_6_prot          (auto_axi4in_xing_in_ar_mem_6_prot),
    .auto_in_ar_mem_6_qos           (auto_axi4in_xing_in_ar_mem_6_qos),
    .auto_in_ar_mem_7_id            (auto_axi4in_xing_in_ar_mem_7_id),
    .auto_in_ar_mem_7_addr          (auto_axi4in_xing_in_ar_mem_7_addr),
    .auto_in_ar_mem_7_len           (auto_axi4in_xing_in_ar_mem_7_len),
    .auto_in_ar_mem_7_size          (auto_axi4in_xing_in_ar_mem_7_size),
    .auto_in_ar_mem_7_burst         (auto_axi4in_xing_in_ar_mem_7_burst),
    .auto_in_ar_mem_7_lock          (auto_axi4in_xing_in_ar_mem_7_lock),
    .auto_in_ar_mem_7_cache         (auto_axi4in_xing_in_ar_mem_7_cache),
    .auto_in_ar_mem_7_prot          (auto_axi4in_xing_in_ar_mem_7_prot),
    .auto_in_ar_mem_7_qos           (auto_axi4in_xing_in_ar_mem_7_qos),
    .auto_in_ar_ridx                (auto_axi4in_xing_in_ar_ridx),
    .auto_in_ar_widx                (auto_axi4in_xing_in_ar_widx),
    .auto_in_ar_safe_ridx_valid     (auto_axi4in_xing_in_ar_safe_ridx_valid),
    .auto_in_ar_safe_widx_valid     (auto_axi4in_xing_in_ar_safe_widx_valid),
    .auto_in_ar_safe_source_reset_n (auto_axi4in_xing_in_ar_safe_source_reset_n),
    .auto_in_ar_safe_sink_reset_n   (auto_axi4in_xing_in_ar_safe_sink_reset_n),
    .auto_in_r_mem_0_id             (auto_axi4in_xing_in_r_mem_0_id),
    .auto_in_r_mem_0_data           (auto_axi4in_xing_in_r_mem_0_data),
    .auto_in_r_mem_0_resp           (auto_axi4in_xing_in_r_mem_0_resp),
    .auto_in_r_mem_0_last           (auto_axi4in_xing_in_r_mem_0_last),
    .auto_in_r_mem_1_id             (auto_axi4in_xing_in_r_mem_1_id),
    .auto_in_r_mem_1_data           (auto_axi4in_xing_in_r_mem_1_data),
    .auto_in_r_mem_1_resp           (auto_axi4in_xing_in_r_mem_1_resp),
    .auto_in_r_mem_1_last           (auto_axi4in_xing_in_r_mem_1_last),
    .auto_in_r_mem_2_id             (auto_axi4in_xing_in_r_mem_2_id),
    .auto_in_r_mem_2_data           (auto_axi4in_xing_in_r_mem_2_data),
    .auto_in_r_mem_2_resp           (auto_axi4in_xing_in_r_mem_2_resp),
    .auto_in_r_mem_2_last           (auto_axi4in_xing_in_r_mem_2_last),
    .auto_in_r_mem_3_id             (auto_axi4in_xing_in_r_mem_3_id),
    .auto_in_r_mem_3_data           (auto_axi4in_xing_in_r_mem_3_data),
    .auto_in_r_mem_3_resp           (auto_axi4in_xing_in_r_mem_3_resp),
    .auto_in_r_mem_3_last           (auto_axi4in_xing_in_r_mem_3_last),
    .auto_in_r_mem_4_id             (auto_axi4in_xing_in_r_mem_4_id),
    .auto_in_r_mem_4_data           (auto_axi4in_xing_in_r_mem_4_data),
    .auto_in_r_mem_4_resp           (auto_axi4in_xing_in_r_mem_4_resp),
    .auto_in_r_mem_4_last           (auto_axi4in_xing_in_r_mem_4_last),
    .auto_in_r_mem_5_id             (auto_axi4in_xing_in_r_mem_5_id),
    .auto_in_r_mem_5_data           (auto_axi4in_xing_in_r_mem_5_data),
    .auto_in_r_mem_5_resp           (auto_axi4in_xing_in_r_mem_5_resp),
    .auto_in_r_mem_5_last           (auto_axi4in_xing_in_r_mem_5_last),
    .auto_in_r_mem_6_id             (auto_axi4in_xing_in_r_mem_6_id),
    .auto_in_r_mem_6_data           (auto_axi4in_xing_in_r_mem_6_data),
    .auto_in_r_mem_6_resp           (auto_axi4in_xing_in_r_mem_6_resp),
    .auto_in_r_mem_6_last           (auto_axi4in_xing_in_r_mem_6_last),
    .auto_in_r_mem_7_id             (auto_axi4in_xing_in_r_mem_7_id),
    .auto_in_r_mem_7_data           (auto_axi4in_xing_in_r_mem_7_data),
    .auto_in_r_mem_7_resp           (auto_axi4in_xing_in_r_mem_7_resp),
    .auto_in_r_mem_7_last           (auto_axi4in_xing_in_r_mem_7_last),
    .auto_in_r_ridx                 (auto_axi4in_xing_in_r_ridx),
    .auto_in_r_widx                 (auto_axi4in_xing_in_r_widx),
    .auto_in_r_safe_ridx_valid      (auto_axi4in_xing_in_r_safe_ridx_valid),
    .auto_in_r_safe_widx_valid      (auto_axi4in_xing_in_r_safe_widx_valid),
    .auto_in_r_safe_source_reset_n  (auto_axi4in_xing_in_r_safe_source_reset_n),
    .auto_in_r_safe_sink_reset_n    (auto_axi4in_xing_in_r_safe_sink_reset_n),
    .auto_out_aw_ready              (_blackbox_s_axi_awready),	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:52:26]
    .auto_out_aw_valid              (_axi4asink_auto_out_aw_valid),
    .auto_out_aw_bits_id            (_axi4asink_auto_out_aw_bits_id),
    .auto_out_aw_bits_addr          (_axi4asink_auto_out_aw_bits_addr),
    .auto_out_aw_bits_len           (_axi4asink_auto_out_aw_bits_len),
    .auto_out_aw_bits_size          (_axi4asink_auto_out_aw_bits_size),
    .auto_out_aw_bits_burst         (_axi4asink_auto_out_aw_bits_burst),
    .auto_out_aw_bits_lock          (_axi4asink_auto_out_aw_bits_lock),
    .auto_out_aw_bits_prot          (_axi4asink_auto_out_aw_bits_prot),
    .auto_out_aw_bits_qos           (_axi4asink_auto_out_aw_bits_qos),
    .auto_out_w_ready               (_blackbox_s_axi_wready),	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:52:26]
    .auto_out_w_valid               (_axi4asink_auto_out_w_valid),
    .auto_out_w_bits_data           (_axi4asink_auto_out_w_bits_data),
    .auto_out_w_bits_strb           (_axi4asink_auto_out_w_bits_strb),
    .auto_out_w_bits_last           (_axi4asink_auto_out_w_bits_last),
    .auto_out_b_ready               (_axi4asink_auto_out_b_ready),
    .auto_out_b_valid               (_blackbox_s_axi_bvalid),	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:52:26]
    .auto_out_b_bits_id             (_blackbox_s_axi_bid),	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:52:26]
    .auto_out_b_bits_resp           (_blackbox_s_axi_bresp),	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:52:26]
    .auto_out_ar_ready              (_blackbox_s_axi_arready),	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:52:26]
    .auto_out_ar_valid              (_axi4asink_auto_out_ar_valid),
    .auto_out_ar_bits_id            (_axi4asink_auto_out_ar_bits_id),
    .auto_out_ar_bits_addr          (_axi4asink_auto_out_ar_bits_addr),
    .auto_out_ar_bits_len           (_axi4asink_auto_out_ar_bits_len),
    .auto_out_ar_bits_size          (_axi4asink_auto_out_ar_bits_size),
    .auto_out_ar_bits_burst         (_axi4asink_auto_out_ar_bits_burst),
    .auto_out_ar_bits_lock          (_axi4asink_auto_out_ar_bits_lock),
    .auto_out_ar_bits_prot          (_axi4asink_auto_out_ar_bits_prot),
    .auto_out_ar_bits_qos           (_axi4asink_auto_out_ar_bits_qos),
    .auto_out_r_ready               (_axi4asink_auto_out_r_ready),
    .auto_out_r_valid               (_blackbox_s_axi_rvalid),	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:52:26]
    .auto_out_r_bits_id             (_blackbox_s_axi_rid),	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:52:26]
    .auto_out_r_bits_data           (_blackbox_s_axi_rdata),	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:52:26]
    .auto_out_r_bits_resp           (_blackbox_s_axi_rresp),	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:52:26]
    .auto_out_r_bits_last           (_blackbox_s_axi_rlast)	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:52:26]
  );
  nexysvideomig blackbox (	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:52:26]
    .ddr3_addr           (io_port_ddr3_addr),
    .ddr3_ba             (io_port_ddr3_ba),
    .ddr3_ras_n          (io_port_ddr3_ras_n),
    .ddr3_cas_n          (io_port_ddr3_cas_n),
    .ddr3_we_n           (io_port_ddr3_we_n),
    .ddr3_reset_n        (io_port_ddr3_reset_n),
    .ddr3_ck_p           (io_port_ddr3_ck_p),
    .ddr3_ck_n           (io_port_ddr3_ck_n),
    .ddr3_cke            (io_port_ddr3_cke),
    .ddr3_dm             (io_port_ddr3_dm),
    .ddr3_odt            (io_port_ddr3_odt),
    .ddr3_dq             (io_port_ddr3_dq),
    .ddr3_dqs_n          (io_port_ddr3_dqs_n),
    .ddr3_dqs_p          (io_port_ddr3_dqs_p),
    .sys_clk_i           (io_port_sys_clk_i),
    .clk_ref_i           (io_port_clk_ref_i),
    .ui_clk              (_blackbox_ui_clk),
    .ui_clk_sync_rst     (_blackbox_ui_clk_sync_rst),
    .mmcm_locked         (io_port_mmcm_locked),
    .aresetn             (io_port_aresetn),
    .init_calib_complete (io_port_init_calib_complete),
    .sys_rst             (io_port_sys_rst),
    .app_sr_req          (1'h0),	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:416:25]
    .app_ref_req         (1'h0),	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:416:25]
    .app_zq_req          (1'h0),	// @[generators/rocket-chip/src/main/scala/diplomacy/LazyModule.scala:416:25]
    .app_sr_active       (/* unused */),
    .app_ref_ack         (/* unused */),
    .app_zq_ack          (/* unused */),
    .s_axi_awid          (_axi4asink_auto_out_aw_bits_id),	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
    .s_axi_awaddr        (_axi4asink_auto_out_aw_bits_addr[29:0]),	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:91:41, generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
    .s_axi_awlen         (_axi4asink_auto_out_aw_bits_len),	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
    .s_axi_awsize        (_axi4asink_auto_out_aw_bits_size),	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
    .s_axi_awburst       (_axi4asink_auto_out_aw_bits_burst),	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
    .s_axi_awlock        (_axi4asink_auto_out_aw_bits_lock),	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
    .s_axi_awcache       (4'h3),	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:101:31]
    .s_axi_awprot        (_axi4asink_auto_out_aw_bits_prot),	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
    .s_axi_awqos         (_axi4asink_auto_out_aw_bits_qos),	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
    .s_axi_awvalid       (_axi4asink_auto_out_aw_valid),	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
    .s_axi_awready       (_blackbox_s_axi_awready),
    .s_axi_wdata         (_axi4asink_auto_out_w_bits_data),	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
    .s_axi_wstrb         (_axi4asink_auto_out_w_bits_strb),	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
    .s_axi_wlast         (_axi4asink_auto_out_w_bits_last),	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
    .s_axi_wvalid        (_axi4asink_auto_out_w_valid),	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
    .s_axi_wready        (_blackbox_s_axi_wready),
    .s_axi_bready        (_axi4asink_auto_out_b_ready),	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
    .s_axi_bid           (_blackbox_s_axi_bid),
    .s_axi_bresp         (_blackbox_s_axi_bresp),
    .s_axi_bvalid        (_blackbox_s_axi_bvalid),
    .s_axi_arid          (_axi4asink_auto_out_ar_bits_id),	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
    .s_axi_araddr        (_axi4asink_auto_out_ar_bits_addr[29:0]),	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:92:41, generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
    .s_axi_arlen         (_axi4asink_auto_out_ar_bits_len),	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
    .s_axi_arsize        (_axi4asink_auto_out_ar_bits_size),	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
    .s_axi_arburst       (_axi4asink_auto_out_ar_bits_burst),	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
    .s_axi_arlock        (_axi4asink_auto_out_ar_bits_lock),	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
    .s_axi_arcache       (4'h3),	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:101:31]
    .s_axi_arprot        (_axi4asink_auto_out_ar_bits_prot),	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
    .s_axi_arqos         (_axi4asink_auto_out_ar_bits_qos),	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
    .s_axi_arvalid       (_axi4asink_auto_out_ar_valid),	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
    .s_axi_arready       (_blackbox_s_axi_arready),
    .s_axi_rready        (_axi4asink_auto_out_r_ready),	// @[generators/rocket-chip/src/main/scala/amba/axi4/AsyncCrossing.scala:72:31]
    .s_axi_rid           (_blackbox_s_axi_rid),
    .s_axi_rdata         (_blackbox_s_axi_rdata),
    .s_axi_rresp         (_blackbox_s_axi_rresp),
    .s_axi_rlast         (_blackbox_s_axi_rlast),
    .s_axi_rvalid        (_blackbox_s_axi_rvalid),
    .device_temp         (/* unused */)
  );
  assign io_port_ui_clk = _blackbox_ui_clk;	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:52:26]
  assign io_port_ui_clk_sync_rst = _blackbox_ui_clk_sync_rst;	// @[fpga/fpga-shells/src/main/scala/devices/xilinx/xilinxnexysvideomig/XilinxNexysVideoMIG.scala:52:26]
endmodule

